set(NODE_TEST_COMPUTE_COMMON_SOURCES
  tests/contract/compute/allocation.cpp
)

set(NODE_TEST_COMPUTE_SOURCES
  tests/contract/compute/numeric.cpp
  tests/contract/compute/telemetry/contract.cpp
  tests/contract/compute/telemetry/profile.cpp
  tests/contract/compute/telemetry/projection.cpp
  tests/contract/compute/fixed/value.cpp
  tests/contract/compute/result.cpp
  tests/contract/compute/error.cpp
  tests/contract/compute/reuse.cpp
  tests/contract/compute/cpu/tiles.cpp
  tests/contract/compute/cpu/view.cpp
  tests/contract/compute/program/cache/concurrency.cpp
  tests/contract/compute/program/cache/concurrency/async.cpp
  tests/contract/compute/program/cache/concurrency/capacity.cpp
  tests/contract/compute/program/cache/concurrency/failure.cpp
  tests/contract/compute/program/cache/concurrency/lifetime.cpp
  tests/contract/compute/program/cache/concurrency/service.cpp
  tests/contract/compute/program/cache/index.cpp
  tests/contract/compute/graph/build.cpp
  tests/contract/compute/graph/services/boundary.cpp
  tests/contract/compute/graph/services/birth.cpp
  tests/contract/compute/graph/services/memory.cpp
  tests/contract/compute/graph/services/plan.cpp
  tests/contract/compute/graph/services/resource.cpp
  tests/contract/compute/flow/primitives.cpp
)

set(NODE_TEST_COMPUTE_ACCEL_SOURCES
  tests/contract/compute/device.cpp
  tests/contract/compute/vulkan/cache.cpp
  tests/contract/compute/map.cpp
  tests/contract/compute/map/local/model.cpp
  tests/contract/compute/map/canonical.cpp
  tests/contract/compute/map/liveness.cpp
  tests/contract/compute/map/envelope.cpp
  tests/contract/compute/map/run.cpp
  tests/contract/compute/fixed/multiply/declared.cpp
  tests/contract/compute/fixed/predicate/wide.cpp
  tests/contract/compute/resident/write.cpp
  tests/contract/compute/flow.cpp
  tests/contract/compute/flow/contract/backend.cpp
  tests/contract/compute/flow/contract/basic.cpp
  tests/contract/compute/flow/contract/compose.cpp
  tests/contract/compute/flow/contract/device.cpp
  tests/contract/compute/flow/contract/expression.cpp
  tests/contract/compute/flow/contract/parity.cpp
  tests/contract/compute/flow/contract/record.cpp
  tests/contract/compute/flow/contract/shape.cpp
  tests/contract/compute/flow/contract/surface.cpp
  tests/contract/compute/flow/numeric.cpp
  tests/contract/compute/flow/numeric/local/model.cpp
  tests/contract/compute/flow/numeric/core.cpp
  tests/contract/compute/flow/numeric/format.cpp
  tests/contract/compute/flow/numeric/modes.cpp
  tests/contract/compute/flow/numeric/modes/algebra.cpp
  tests/contract/compute/flow/numeric/modes/golden.cpp
  tests/contract/compute/flow/numeric/modes/policy.cpp
  tests/contract/compute/flow/numeric/modes/transform.cpp
)

# A semantic leaf belongs to the registered case that calls it. Exact-focus and
# subset targets use this one table to exclude unrelated leaves while keeping
# unmapped support sources global. One row may name multiple cases when they
# deliberately share one fixture authority.
list(APPEND RUND_NODE_TEST_COMPANION_ROWS
  "tests/contract/compute/telemetry/profile.cpp|compute.telemetry"
  "tests/contract/compute/telemetry/projection.cpp|compute.telemetry"
  "tests/contract/compute/cpu/view.cpp|compute.cpu-tiles"
  "tests/contract/compute/map/local/model.cpp|compute.map"
  "tests/contract/compute/map/canonical.cpp|compute.map"
  "tests/contract/compute/map/liveness.cpp|compute.map"
  "tests/contract/compute/map/envelope.cpp|compute.map"
  "tests/contract/compute/map/run.cpp|compute.map"
  "tests/contract/compute/flow/numeric/local/model.cpp|compute.flow-numeric-accel,compute.flow-numeric-modes"
  "tests/contract/compute/flow/numeric/core.cpp|compute.flow-numeric-accel,compute.flow-numeric-modes"
  "tests/contract/compute/flow/numeric/format.cpp|compute.flow-numeric-accel,compute.flow-numeric-modes"
  "tests/contract/compute/flow/numeric/modes/algebra.cpp|compute.flow-numeric-accel,compute.flow-numeric-modes"
  "tests/contract/compute/flow/numeric/modes/golden.cpp|compute.flow-numeric-accel,compute.flow-numeric-modes"
  "tests/contract/compute/flow/numeric/modes/policy.cpp|compute.flow-numeric-accel,compute.flow-numeric-modes"
  "tests/contract/compute/flow/numeric/modes/transform.cpp|compute.flow-numeric-accel,compute.flow-numeric-modes"
  "tests/contract/compute/graph/services/boundary.cpp|compute.graph-plan"
  "tests/contract/compute/graph/services/birth.cpp|compute.graph-plan"
  "tests/contract/compute/graph/services/memory.cpp|compute.graph-plan"
  "tests/contract/compute/graph/services/resource.cpp|compute.graph-plan"
  "tests/contract/compute/flow/shape/local/model.cpp|compute.static-matrix"
  "tests/contract/compute/flow/shape/surface.cpp|compute.static-matrix"
  "tests/contract/compute/flow/shape/run.cpp|compute.static-matrix"
  "tests/contract/compute/pipeline/backend.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/binding.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/chunk.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/checkpoint.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/completion.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/empty.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/sealed.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/fixed.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/feedback.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/hazard.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/history.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/oracle.cpp|compute.pipeline,compute.window"
  "tests/contract/compute/pipeline/identity.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/loss.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/metal.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/metal/residency.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/vulkan/transfer.cpp|compute.pipeline,compute.pipeline-vulkan-transfer"
  "tests/contract/compute/pipeline/memory.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/admission.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/profile/steps.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/profile/samples.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/range/introspection.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/range/resident.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/repeat.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/state.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/status.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/surface.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/views.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/view/arena.cpp|compute.pipeline"
  "tests/contract/compute/pipeline/transfer/model.cpp|compute.pipeline-transfer"
  "tests/contract/compute/pipeline/transfer/success.cpp|compute.pipeline-transfer"
  "tests/contract/compute/pipeline/transfer/failure.cpp|compute.pipeline-transfer"
  "tests/contract/compute/pipeline/transfer/download.cpp|compute.pipeline-transfer"
  "tests/contract/compute/pipeline/residency/planner.cpp|compute.pipeline-residency"
  "tests/contract/compute/pipeline/residency/identity.cpp|compute.pipeline-residency"
  "tests/contract/compute/virtual/backing.cpp|compute.virtual-residency-oracle"
  "tests/contract/compute/virtual/golden.cpp|compute.virtual-residency-oracle"
  "tests/contract/compute/virtual/pager.cpp|compute.virtual-residency-oracle"
  "tests/contract/compute/virtual/oracle.cpp|compute.virtual-residency-oracle"
  "tests/contract/compute/virtual/product/backing.cpp|compute.virtual-residency-product"
  "tests/contract/compute/virtual/product/active.cpp|compute.virtual-residency-product"
  "tests/contract/compute/virtual/product/golden.cpp|compute.virtual-residency-product"
  "tests/contract/compute/virtual/product/evidence.cpp|compute.virtual-residency-product"
  "tests/contract/compute/virtual/product/surface.cpp|compute.virtual-residency-product"
  "tests/contract/compute/virtual/product/capability.cpp|compute.virtual-residency-product"
  "tests/contract/compute/virtual/product/prepare.cpp|compute.virtual-residency-product"
  "tests/contract/compute/virtual/product/execution.cpp|compute.virtual-residency-product"
  "tests/contract/compute/virtual/product/failure.cpp|compute.virtual-residency-product"
  "tests/contract/compute/virtual/product/width.cpp|compute.virtual-residency-product"
  "tests/contract/compute/virtual/product/concurrency/local.cpp|compute.virtual-residency-product"
  "tests/contract/compute/virtual/product/concurrency/pipeline.cpp|compute.virtual-residency-product"
  "tests/contract/compute/virtual/product/concurrency/backing.cpp|compute.virtual-residency-product"
  "tests/contract/compute/window/chain.cpp|compute.window"
  "tests/contract/compute/window/freeze.cpp|compute.window"
  "tests/contract/compute/window/matrix.cpp|compute.window"
  "tests/contract/compute/window/nested/contract.cpp|compute.window"
  "tests/contract/compute/window/nested/control.cpp|compute.window"
  "tests/contract/compute/window/nested/evidence.cpp|compute.window"
  "tests/contract/compute/window/nested/execution.cpp|compute.window"
  "tests/contract/compute/window/nested/failure.cpp|compute.window"
  "tests/contract/compute/window/nested/fixture.cpp|compute.window"
  "tests/contract/compute/window/nested/identity.cpp|compute.window"
  "tests/contract/compute/window/nested/oracle.cpp|compute.window"
  "tests/contract/compute/window/nested/plan.cpp|compute.window"
  "tests/contract/compute/window/nested/program.cpp|compute.window"
  "tests/contract/compute/window/output/contract.cpp|compute.window"
  "tests/contract/compute/window/output/control.cpp|compute.window"
  "tests/contract/compute/window/output/execution.cpp|compute.window"
  "tests/contract/compute/window/output/failure.cpp|compute.window"
  "tests/contract/compute/window/output/model.cpp|compute.window"
  "tests/contract/compute/window/output/ordinary.cpp|compute.window"
  "tests/contract/compute/window/output/publication.cpp|compute.window"
  "tests/contract/compute/window/output/publication_mutation.cpp|compute.window"
  "tests/contract/compute/window/output/subview.cpp|compute.window"
  "tests/contract/compute/window/parity.cpp|compute.window"
  "tests/contract/compute/window/plan.cpp|compute.window"
  "tests/contract/compute/window/terminal.cpp|compute.window"
  "tests/contract/compute/window/workset.cpp|compute.window"
  "tests/contract/compute/memory/accel.cpp|compute.memory"
  "tests/contract/compute/memory/arena.cpp|compute.memory"
  "tests/contract/compute/memory/cpu_arena.cpp|compute.memory"
  "tests/contract/compute/memory/graph.cpp|compute.memory"
  "tests/contract/compute/memory/observe.cpp|compute.memory"
  "tests/contract/compute/memory/program.cpp|compute.memory"
  "tests/contract/compute/memory/scratch.cpp|compute.memory"
  "tests/contract/compute/backend/domain.cpp|compute.backend"
  "tests/contract/compute/backend/map.cpp|compute.backend"
  "tests/contract/compute/backend/matrix.cpp|compute.backend"
  "tests/contract/compute/backend/movement.cpp|compute.backend"
  "tests/contract/compute/backend/observe.cpp|compute.backend"
  "tests/contract/compute/backend/primitive.cpp|compute.backend"
  "tests/contract/compute/backend/segment.cpp|compute.backend"
  "tests/contract/compute/collective/modes/backend.cpp|compute.collective-modes"
  "tests/contract/compute/collective/modes/bounded.cpp|compute.collective-modes"
  "tests/contract/compute/collective/modes/cancel.cpp|compute.collective-modes"
  "tests/contract/compute/collective/modes/core.cpp|compute.collective-modes"
  "tests/contract/compute/collective/modes/empty.cpp|compute.collective-modes"
  "tests/contract/compute/collective/modes/overflow.cpp|compute.collective-modes"
  "tests/contract/compute/collective/modes/reduce.cpp|compute.collective-modes"
  "tests/contract/compute/collective/modes/scale.cpp|compute.collective-modes"
  "tests/contract/compute/bounded/backend.cpp|compute.bounded-parity"
  "tests/contract/compute/bounded/compact.cpp|compute.bounded-parity"
  "tests/contract/compute/bounded/cpu.cpp|compute.bounded-parity"
  "tests/contract/compute/bounded/expand.cpp|compute.bounded-parity"
  "tests/contract/compute/bounded/filter.cpp|compute.bounded-parity"
  "tests/contract/compute/bounded/group.cpp|compute.bounded-parity"
  "tests/contract/compute/bounded/invalid.cpp|compute.bounded-parity"
  "tests/contract/compute/bounded/parity.cpp|compute.bounded-parity"
  "tests/contract/compute/bounded/rewrite.cpp|compute.bounded-parity"
  "tests/contract/compute/bounded/surface.cpp|compute.bounded-parity"
  "tests/contract/compute/bounded/vulkan.cpp|compute.bounded-parity"
  "tests/contract/compute/graph/services/async.cpp|compute.graph-services"
  "tests/contract/compute/graph/services/backend.cpp|compute.graph-services"
  "tests/contract/compute/graph/services/bounded.cpp|compute.graph-services"
  "tests/contract/compute/graph/services/cache.cpp|compute.graph-services"
  "tests/contract/compute/graph/services/empty.cpp|compute.graph-services"
  "tests/contract/compute/graph/services/fixed.cpp|compute.graph-services"
  "tests/contract/compute/graph/services/oracle.cpp|compute.graph-services"
  "tests/contract/compute/graph/services/identity.cpp|compute.graph-services"
  "tests/contract/compute/graph/services/memory/reuse.cpp|compute.graph-services"
  "tests/contract/compute/graph/services/policy.cpp|compute.graph-services"
)

set(NODE_TEST_COMPUTE_EXPRESSIONS_SOURCES
  tests/contract/compute/expression/contract.cpp
  tests/contract/compute/expression/integral.cpp
  tests/contract/compute/expression/fixed/core.cpp
  tests/contract/compute/expression/fixed/policy.cpp
  tests/contract/compute/expression/function/core.cpp
  tests/contract/compute/expression/function/fixed/32/linear.cpp
  tests/contract/compute/expression/function/fixed/64/linear.cpp
  tests/contract/compute/expression/function/geometry.cpp
  tests/contract/compute/expression/function/algebra.cpp
  tests/contract/compute/expression/function/approx.cpp
  tests/contract/compute/expression/function/golden.cpp
  tests/contract/compute/expression/cardinality.cpp
)

set(NODE_TEST_COMPUTE_LINE_TABLE_SOURCES
  ${NODE_TEST_COMPUTE_EXPRESSIONS_SOURCES}
  tests/contract/compute/memory.cpp
  tests/contract/compute/memory/accel.cpp
  tests/contract/compute/memory/arena.cpp
  tests/contract/compute/memory/cpu_arena.cpp
  tests/contract/compute/memory/graph.cpp
  tests/contract/compute/memory/observe.cpp
  tests/contract/compute/memory/program.cpp
  tests/contract/compute/memory/scratch.cpp
)

# These executable contracts print their own value/backend diagnostics. Keep
# source lines for sanitizer and crash symbolization without emitting the full
# template-local DWARF graph in Debug builds.
set_property(SOURCE ${NODE_TEST_COMPUTE_LINE_TABLE_SOURCES}
  APPEND PROPERTY COMPILE_OPTIONS
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANG_AND_ID:CXX,AppleClang,Clang>>:-gline-tables-only>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANG_AND_ID:CXX,GNU>>:-g1>")

set(NODE_TEST_COMPUTE_EXECUTION_SOURCES
  tests/contract/compute/flow/shape.cpp
  tests/contract/compute/flow/shape/local/model.cpp
  tests/contract/compute/flow/shape/surface.cpp
  tests/contract/compute/flow/shape/run.cpp
  tests/contract/compute/batch.cpp
  tests/contract/compute/job.cpp
  tests/contract/compute/pipeline.cpp
  tests/contract/compute/pipeline/backend.cpp
  tests/contract/compute/pipeline/binding.cpp
  tests/contract/compute/pipeline/chunk.cpp
  tests/contract/compute/pipeline/checkpoint.cpp
  tests/contract/compute/pipeline/completion.cpp
  tests/contract/compute/pipeline/empty.cpp
  tests/contract/compute/pipeline/sealed.cpp
  tests/contract/compute/pipeline/fixed.cpp
  tests/contract/compute/pipeline/feedback.cpp
  tests/contract/compute/pipeline/hazard.cpp
  tests/contract/compute/pipeline/history.cpp
  tests/contract/compute/pipeline/oracle.cpp
  tests/contract/compute/pipeline/identity.cpp
  tests/contract/compute/pipeline/loss.cpp
  tests/contract/compute/pipeline/metal.cpp
  tests/contract/compute/pipeline/metal/residency.cpp
  tests/contract/compute/pipeline/vulkan/contract.cpp
  tests/contract/compute/pipeline/vulkan/transfer.cpp
  tests/contract/compute/pipeline/memory.cpp
  tests/contract/compute/pipeline/admission.cpp
  tests/contract/compute/pipeline/profile/steps.cpp
  tests/contract/compute/pipeline/profile/samples.cpp
  tests/contract/compute/pipeline/range/introspection.cpp
  tests/contract/compute/pipeline/range/resident.cpp
  tests/contract/compute/pipeline/repeat.cpp
  tests/contract/compute/pipeline/state.cpp
  tests/contract/compute/pipeline/status.cpp
  tests/contract/compute/pipeline/surface.cpp
  tests/contract/compute/pipeline/views.cpp
  tests/contract/compute/pipeline/view/arena.cpp
  tests/contract/compute/pipeline/transfer/contract.cpp
  tests/contract/compute/pipeline/transfer/model.cpp
  tests/contract/compute/pipeline/transfer/success.cpp
  tests/contract/compute/pipeline/transfer/failure.cpp
  tests/contract/compute/pipeline/transfer/download.cpp
  tests/contract/compute/pipeline/residency/contract.cpp
  tests/contract/compute/pipeline/residency/planner.cpp
  tests/contract/compute/pipeline/residency/identity.cpp
  tests/contract/compute/virtual/contract.cpp
  tests/contract/compute/virtual/backing.cpp
  tests/contract/compute/virtual/golden.cpp
  tests/contract/compute/virtual/pager.cpp
  tests/contract/compute/virtual/oracle.cpp
  tests/contract/compute/virtual/product/contract.cpp
  tests/contract/compute/virtual/product/active.cpp
  tests/contract/compute/virtual/product/backing.cpp
  tests/contract/compute/virtual/product/golden.cpp
  tests/contract/compute/virtual/product/evidence.cpp
  tests/contract/compute/virtual/product/surface.cpp
  tests/contract/compute/virtual/product/capability.cpp
  tests/contract/compute/virtual/product/prepare.cpp
  tests/contract/compute/virtual/product/execution.cpp
  tests/contract/compute/virtual/product/failure.cpp
  tests/contract/compute/virtual/product/width.cpp
  tests/contract/compute/virtual/product/concurrency/local.cpp
  tests/contract/compute/virtual/product/concurrency/pipeline.cpp
  tests/contract/compute/virtual/product/concurrency/backing.cpp
  tests/contract/compute/window.cpp
  tests/contract/compute/window/chain.cpp
  tests/contract/compute/window/freeze.cpp
  tests/contract/compute/window/matrix.cpp
  tests/contract/compute/window/nested/contract.cpp
  tests/contract/compute/window/nested/control.cpp
  tests/contract/compute/window/nested/evidence.cpp
  tests/contract/compute/window/nested/execution.cpp
  tests/contract/compute/window/nested/failure.cpp
  tests/contract/compute/window/nested/fixture.cpp
  tests/contract/compute/window/nested/identity.cpp
  tests/contract/compute/window/nested/oracle.cpp
  tests/contract/compute/window/nested/plan.cpp
  tests/contract/compute/window/nested/program.cpp
  tests/contract/compute/window/output/contract.cpp
  tests/contract/compute/window/output/control.cpp
  tests/contract/compute/window/output/execution.cpp
  tests/contract/compute/window/output/failure.cpp
  tests/contract/compute/window/output/model.cpp
  tests/contract/compute/window/output/ordinary.cpp
  tests/contract/compute/window/output/publication.cpp
  tests/contract/compute/window/output/publication_mutation.cpp
  tests/contract/compute/window/output/subview.cpp
  tests/contract/compute/window/parity.cpp
  tests/contract/compute/window/plan.cpp
  tests/contract/compute/window/terminal.cpp
  tests/contract/compute/window/workset.cpp
  tests/contract/compute/memory.cpp
  tests/contract/compute/memory/accel.cpp
  tests/contract/compute/memory/arena.cpp
  tests/contract/compute/memory/cpu_arena.cpp
  tests/contract/compute/memory/graph.cpp
  tests/contract/compute/memory/observe.cpp
  tests/contract/compute/memory/program.cpp
  tests/contract/compute/memory/scratch.cpp
  tests/contract/compute/backend.cpp
  tests/contract/compute/backend/domain.cpp
  tests/contract/compute/backend/map.cpp
  tests/contract/compute/backend/matrix.cpp
  tests/contract/compute/backend/movement.cpp
  tests/contract/compute/backend/observe.cpp
  tests/contract/compute/backend/primitive.cpp
  tests/contract/compute/backend/segment.cpp
  tests/contract/compute/collective/modes.cpp
  tests/contract/compute/collective/modes/backend.cpp
  tests/contract/compute/collective/modes/bounded.cpp
  tests/contract/compute/collective/modes/cancel.cpp
  tests/contract/compute/collective/modes/core.cpp
  tests/contract/compute/collective/modes/empty.cpp
  tests/contract/compute/collective/modes/overflow.cpp
  tests/contract/compute/collective/modes/reduce.cpp
  tests/contract/compute/collective/modes/scale.cpp
  tests/contract/compute/boundary/modes.cpp
  tests/contract/compute/bounded.cpp
  tests/contract/compute/bounded/backend.cpp
  tests/contract/compute/bounded/compact.cpp
  tests/contract/compute/bounded/cpu.cpp
  tests/contract/compute/bounded/expand.cpp
  tests/contract/compute/bounded/filter.cpp
  tests/contract/compute/bounded/group.cpp
  tests/contract/compute/bounded/invalid.cpp
  tests/contract/compute/bounded/parity.cpp
  tests/contract/compute/bounded/rewrite.cpp
  tests/contract/compute/bounded/surface.cpp
  tests/contract/compute/bounded/vulkan.cpp
  tests/contract/compute/graph/services.cpp
  tests/contract/compute/graph/services/async.cpp
  tests/contract/compute/graph/services/backend.cpp
  tests/contract/compute/graph/services/bounded.cpp
  tests/contract/compute/graph/services/cache.cpp
  tests/contract/compute/graph/services/empty.cpp
  tests/contract/compute/graph/services/fixed.cpp
  tests/contract/compute/graph/services/oracle.cpp
  tests/contract/compute/graph/services/identity.cpp
  tests/contract/compute/graph/services/memory/reuse.cpp
  tests/contract/compute/graph/services/policy.cpp
)
