list(APPEND NODE_SOURCES
  src/runtime/task/scheduler/core/host.cpp
  src/runtime/task/scheduler/core/identity.cpp
  src/runtime/task/scheduler/core/replay.cpp
  src/runtime/task/scheduler/core/record/observation.cpp
  src/runtime/task/scheduler/core/record/physical.cpp
  src/runtime/task/scheduler/core/record/root.cpp
  src/runtime/task/scheduler/core/record/task/identity.cpp
  src/runtime/task/scheduler/core/record/task/lifecycle.cpp
  src/runtime/task/scheduler/core/record/task/wait.cpp
  src/runtime/task/scheduler/core/record/task/resources.cpp
  src/runtime/task/scheduler/core/resource/stats.cpp
  src/runtime/task/scheduler/core/reset.cpp
  src/runtime/task/scheduler/core/reset/replay.cpp
  src/runtime/task/scheduler/core/snapshot.cpp
  src/runtime/task/scheduler/core/spawn.cpp
  src/runtime/task/scheduler/core/spawn/budget.cpp
  src/runtime/task/scheduler/core/spawn/enqueue.cpp
  src/runtime/task/scheduler/core/spawn/record.cpp
  src/runtime/task/scheduler/core/spawn/identity.cpp
  src/runtime/task/scheduler/core/spawn/prepare.cpp
  src/runtime/task/scheduler/core/spawn/reject.cpp
  src/runtime/task/scheduler/core/time.cpp
  src/runtime/task/scheduler/task/frame.cpp
  src/runtime/task/scheduler/task/frame/bind.cpp
  src/runtime/task/scheduler/task/callable/pool.cpp
  src/runtime/task/scheduler/task/completion/pool.cpp
  src/runtime/task/scheduler/task/completion/result.cpp
  src/runtime/task/scheduler/task/completion/state.cpp
  src/runtime/task/scheduler/task/completion/wait.cpp
)
