list(APPEND NODE_SOURCES
  src/runtime/task/scheduler/lane/batch.cpp
  src/runtime/task/scheduler/lane/completion.cpp
  src/runtime/task/scheduler/lane/dispatch.cpp
  src/runtime/task/scheduler/lane/residual/policy.cpp
  src/runtime/task/scheduler/lane/segment/commit.cpp
  src/runtime/task/scheduler/lane/segment/commit/collect.cpp
  src/runtime/task/scheduler/lane/segment/commit/effects.cpp
  src/runtime/task/scheduler/lane/segment/commit/side/exit.cpp
  src/runtime/task/scheduler/lane/segment/commit/terminal.cpp
  src/runtime/task/scheduler/lane/segment/commit/trap.cpp
  src/runtime/task/scheduler/lane/segment/dispatch.cpp
  src/runtime/task/scheduler/lane/segment/drain.cpp
  src/runtime/task/scheduler/lane/segment/plan.cpp
  src/runtime/task/scheduler/lane/segment/run.cpp
  src/runtime/task/scheduler/lane/worker/claim/frame.cpp
  src/runtime/task/scheduler/lane/worker/claim/direct.cpp
  src/runtime/task/scheduler/lane/worker/claim/external.cpp
  src/runtime/task/scheduler/lane/worker/claim/mailbox.cpp
  src/runtime/task/scheduler/lane/worker/claim/regular.cpp
  src/runtime/task/scheduler/lane/worker/claim/segment.cpp
  src/runtime/task/scheduler/lane/worker/claim/work.cpp
  src/runtime/task/scheduler/lane/worker/claim.cpp
  src/runtime/task/scheduler/lane/work.cpp
  src/runtime/task/scheduler/lane/worker/publish.cpp
  src/runtime/task/scheduler/lane/worker/run.cpp
  src/runtime/task/scheduler/lane/worker.cpp
)
