list(APPEND NODE_SOURCES
  src/runtime/task/scheduler/reactor/apply/policy.cpp
  src/runtime/task/scheduler/reactor/backlog.cpp
  src/runtime/task/scheduler/reactor/backend.cpp
  src/runtime/task/scheduler/reactor/budget.cpp
  src/runtime/task/scheduler/reactor/cleanup/route.cpp
  src/runtime/task/scheduler/reactor/cleanup/group.cpp
  src/runtime/task/scheduler/reactor/cleanup/removed.cpp
  src/runtime/task/scheduler/reactor/cleanup/timeout.cpp
  src/runtime/task/scheduler/reactor/cleanup/wait.cpp
  src/runtime/task/scheduler/reactor/cleanup/wake.cpp
  src/runtime/task/scheduler/reactor/change/queue.cpp
  src/runtime/task/scheduler/reactor/close.cpp
  src/runtime/task/scheduler/reactor/drain/batch.cpp
  src/runtime/task/scheduler/reactor/drain.cpp
  src/runtime/task/scheduler/reactor/drain/ready.cpp
  src/runtime/task/scheduler/reactor/expand.cpp
  src/runtime/task/scheduler/reactor/generation.cpp
  src/runtime/task/scheduler/reactor/invariants.cpp
  src/runtime/task/scheduler/reactor/many/probe/dispatch.cpp
  src/runtime/task/scheduler/reactor/many/drain.cpp
  src/runtime/task/scheduler/reactor/many/entry.cpp
  src/runtime/task/scheduler/reactor/many/immediate.cpp
  src/runtime/task/scheduler/reactor/many/fairness.cpp
  src/runtime/task/scheduler/reactor/many/park.cpp
  src/runtime/task/scheduler/reactor/many/park/register.cpp
  src/runtime/task/scheduler/reactor/many/park/timer.cpp
  src/runtime/task/scheduler/reactor/many/resume/cleanup.cpp
  src/runtime/task/scheduler/reactor/many/resume/record.cpp
  src/runtime/task/scheduler/reactor/many/resume/result.cpp
  src/runtime/task/scheduler/reactor/many/resume.cpp
  src/runtime/task/scheduler/reactor/many/events.cpp
  src/runtime/task/scheduler/reactor/many/store.cpp
  src/runtime/task/scheduler/reactor/order.cpp
  src/runtime/task/scheduler/reactor/diagnostic/platform.cpp
  src/runtime/task/scheduler/reactor/poll.cpp
  src/runtime/task/scheduler/reactor/many/probe/raw.cpp
  src/runtime/task/scheduler/reactor/ready/set/result.cpp
  src/runtime/task/scheduler/reactor/ready/set/lifecycle.cpp
  src/runtime/task/scheduler/reactor/ready/set/membership.cpp
  src/runtime/task/scheduler/reactor/ready/set/wait.cpp
  src/runtime/task/scheduler/reactor/ready/set/store.cpp
  src/runtime/task/scheduler/reactor/record.cpp
  src/runtime/task/scheduler/reactor/registration.cpp
  src/runtime/task/scheduler/reactor/registry.cpp
  src/runtime/task/scheduler/reactor/scratch.cpp
  src/runtime/task/scheduler/reactor/state.cpp
  src/runtime/task/scheduler/reactor/stats.cpp
  src/runtime/task/scheduler/reactor/timeout.cpp
  src/runtime/task/scheduler/reactor/timeout/immediate.cpp
  src/runtime/task/scheduler/reactor/timeout/park.cpp
  src/runtime/task/scheduler/reactor/timeout/resume.cpp
  src/runtime/task/scheduler/reactor/timeout/storage.cpp
  src/runtime/task/scheduler/reactor/timeout/validate.cpp
  src/runtime/task/scheduler/reactor/timeout/wake.cpp
  src/runtime/task/scheduler/reactor/wait.cpp
  src/runtime/task/scheduler/reactor/wake.cpp
)
