#include "backend.hpp"

#include "format.hpp"

namespace rund::measure::compute::preparation_memory::report {

void PrintBackendFields(const PreparationMemoryObservation &observed) {
  PrintUnsigned(observed.backend_limit.fingerprint_hi);
  PrintUnsigned(observed.backend_limit.fingerprint_lo);
  PrintUnsigned(observed.backend_limit.host_bytes);
  PrintUnsigned(observed.backend_consumed.host_bytes);
  PrintUnsigned(observed.backend_limit.native_bytes);
  PrintUnsigned(observed.backend_consumed.native_bytes);
  PrintUnsigned(observed.backend_limit.template_source_bytes);
  PrintUnsigned(observed.backend_consumed.template_source_bytes);
  PrintUnsigned(observed.backend_limit.source_transient_bytes);
  PrintUnsigned(observed.backend_consumed.source_transient_bytes);
  PrintUnsigned(observed.backend_limit.host_transient_bytes);
  PrintUnsigned(observed.backend_consumed.host_transient_bytes);
  PrintUnsigned(observed.backend_limit.map_recurrence.group_count);
  PrintUnsigned(observed.backend_consumed.map_recurrence.group_count);
  PrintUnsigned(observed.backend_limit.map_recurrence.history_group_count);
  PrintUnsigned(observed.backend_consumed.map_recurrence.history_group_count);
  PrintUnsigned(observed.backend_limit.map_recurrence.template_count);
  PrintUnsigned(observed.backend_consumed.map_recurrence.template_count);
  PrintUnsigned(
      observed.backend_limit.map_recurrence.terminal_template_group_capacity);
  PrintUnsigned(observed.backend_consumed.map_recurrence
                    .terminal_template_group_capacity);
  PrintUnsigned(
      observed.backend_limit.map_recurrence.history_template_group_capacity);
  PrintUnsigned(
      observed.backend_consumed.map_recurrence.history_template_group_capacity);
  PrintUnsigned(observed.backend_limit.map_recurrence.route_host_bytes);
  PrintUnsigned(observed.backend_consumed.map_recurrence.route_host_bytes);
  PrintUnsigned(observed.backend_limit.map_recurrence.template_host_bytes);
  PrintUnsigned(observed.backend_consumed.map_recurrence.template_host_bytes);
  PrintUnsigned(observed.backend_limit.map_recurrence.template_source_bytes);
  PrintUnsigned(observed.backend_consumed.map_recurrence.template_source_bytes);
  PrintUnsigned(observed.backend_limit.map_recurrence.descriptor_set_count);
  PrintUnsigned(observed.backend_consumed.map_recurrence.descriptor_set_count);
  PrintUnsigned(observed.backend_limit.map_recurrence.descriptor_count);
  PrintUnsigned(observed.backend_consumed.map_recurrence.descriptor_count);
  PrintUnsigned(
      observed.backend_limit.map_recurrence.route_native_allocation_count);
  PrintUnsigned(
      observed.backend_consumed.map_recurrence.route_native_allocation_count);
  PrintUnsigned(
      observed.backend_limit.map_recurrence.template_native_allocation_count);
  PrintUnsigned(observed.backend_consumed.map_recurrence
                    .template_native_allocation_count);
  PrintUnsigned(observed.backend_limit.route_count);
  PrintUnsigned(observed.backend_consumed.route_count);
  PrintUnsigned(observed.backend_limit.template_count);
  PrintUnsigned(observed.backend_consumed.template_count);
  PrintUnsigned(observed.backend_limit.occurrence_count);
  PrintUnsigned(observed.backend_consumed.occurrence_count);
  PrintUnsigned(observed.backend_limit.backend_dispatch_count);
  PrintUnsigned(observed.backend_consumed.backend_dispatch_count);
  PrintUnsigned(observed.backend_limit.backend_reset_dispatch_count);
  PrintUnsigned(observed.backend_consumed.backend_reset_dispatch_count);
  PrintUnsigned(observed.backend_limit.backend_window_dispatch_count);
  PrintUnsigned(observed.backend_consumed.backend_window_dispatch_count);
  PrintUnsigned(observed.backend_limit.backend_indirect_dispatch_count);
  PrintUnsigned(observed.backend_consumed.backend_indirect_dispatch_count);
  PrintUnsigned(observed.backend_limit.backend_step_occurrence_count);
  PrintUnsigned(observed.backend_consumed.backend_step_occurrence_count);
  PrintUnsigned(observed.backend_limit.backend_command_count);
  PrintUnsigned(observed.backend_consumed.backend_command_count);
  PrintUnsigned(observed.backend_limit.backend_command_chunk_count);
  PrintUnsigned(observed.backend_consumed.backend_command_chunk_count);
  PrintUnsigned(observed.backend_limit.backend_command_native_bytes);
  PrintUnsigned(observed.backend_consumed.backend_command_native_bytes);
  PrintUnsigned(observed.backend_limit.backend_step_description_count);
  PrintUnsigned(observed.backend_consumed.backend_step_description_count);
  PrintUnsigned(observed.backend_limit.backend_status_source_count);
  PrintUnsigned(observed.backend_consumed.backend_status_source_count);
  PrintUnsigned(observed.backend_limit.backend_status_entry_count);
  PrintUnsigned(observed.backend_consumed.backend_status_entry_count);
  PrintUnsigned(observed.backend_limit.backend_telemetry_count);
  PrintUnsigned(observed.backend_consumed.backend_telemetry_count);
  PrintUnsigned(observed.backend_limit.backend_status_command_count);
  PrintUnsigned(observed.backend_consumed.backend_status_command_count);
  PrintUnsigned(observed.backend_limit.backend_telemetry_command_count);
  PrintUnsigned(observed.backend_consumed.backend_telemetry_command_count);
  PrintUnsigned(observed.backend_limit.backend_window_control_command_count);
  PrintUnsigned(observed.backend_consumed.backend_window_control_command_count);
  PrintUnsigned(observed.backend_limit.backend_publication_command_count);
  PrintUnsigned(observed.backend_consumed.backend_publication_command_count);
  PrintUnsigned(observed.backend_limit.backend_parameter_bytes);
  PrintUnsigned(observed.backend_consumed.backend_parameter_bytes);
  PrintUnsigned(observed.backend_limit.descriptor_set_count);
  PrintUnsigned(observed.backend_consumed.descriptor_set_count);
  PrintUnsigned(observed.backend_limit.descriptor_count);
  PrintUnsigned(observed.backend_consumed.descriptor_count);
  PrintUnsigned(observed.backend_limit.native_allocation_count);
  PrintUnsigned(observed.backend_consumed.native_allocation_count);
  PrintUnsigned(observed.backend_limit.backend_native_object_count);
  PrintUnsigned(observed.backend_consumed.backend_native_object_count);
}

} // namespace rund::measure::compute::preparation_memory::report
