include_guard(GLOBAL)

function(rund_node_test_tag_valid out tag)
  if(tag MATCHES
     "^[A-Za-z][A-Za-z0-9_-]*(:[A-Za-z][A-Za-z0-9_-]*)*$")
    set(${out} TRUE PARENT_SCOPE)
  else()
    set(${out} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(rund_node_require_test_tag tag)
  rund_node_test_tag_valid(valid "${tag}")
  if(NOT valid)
    message(FATAL_ERROR "Malformed Node test tag: ${tag}")
  endif()
endfunction()

function(rund_node_require_test_tags tags)
  if(tags STREQUAL "-")
    return()
  endif()
  if(tags MATCHES "(^[+]|[+]$|[+][+])")
    message(FATAL_ERROR "Malformed Node test tags: ${tags}")
  endif()
  string(REPLACE "+" ";" entries "${tags}")
  set(unique ${entries})
  list(REMOVE_DUPLICATES unique)
  if(NOT "${unique}" STREQUAL "${entries}")
    message(FATAL_ERROR "Duplicate Node test tag: ${tags}")
  endif()
  foreach(entry IN LISTS entries)
    rund_node_require_test_tag("${entry}")
  endforeach()
endfunction()

function(rund_node_registry_track path)
  get_filename_component(path "${path}" ABSOLUTE)
  set_property(GLOBAL APPEND PROPERTY RUND_NODE_REGISTRY_INPUTS "${path}")
  if(NOT CMAKE_SCRIPT_MODE_FILE)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
  endif()
endfunction()

function(rund_node_registry_fragment file group suite)
  get_filename_component(path "${file}" ABSOLUTE)
  set(chain ${ARGN})
  list(FIND chain "${path}" cycle_index)
  if(NOT cycle_index EQUAL -1)
    message(FATAL_ERROR "Cyclic node test case include: ${path}")
  endif()
  list(APPEND chain "${path}")

  rund_node_registry_track("${path}")
  get_filename_component(dir "${path}" DIRECTORY)
  file(STRINGS "${path}" lines)

  foreach(line IN LISTS lines)
    string(STRIP "${line}" line)
    if(line STREQUAL "" OR line MATCHES "^//")
      continue()
    endif()
    if(line MATCHES "^#include[ \t]+\"([^\"]+)\"$")
      set(relative "${CMAKE_MATCH_1}")
      string(REPLACE "/" ";" path_parts "${relative}")
      list(FIND path_parts ".." parent_index)
      if(IS_ABSOLUTE "${relative}" OR NOT parent_index EQUAL -1)
        message(FATAL_ERROR
          "Node test case include must stay below its fragment: ${line}")
      endif()
      set(next "${dir}/${relative}")
      if(NOT EXISTS "${next}" OR IS_DIRECTORY "${next}")
        message(FATAL_ERROR "Missing node test case fragment: ${next}")
      endif()
      rund_node_registry_fragment("${next}" "${group}" "${suite}" ${chain})
      continue()
    endif()

    set(profile product)
    set(tags "-")
    if(line MATCHES
       "^RUND_NODE_TEST_CASE\\(\"([A-Za-z0-9][A-Za-z0-9_.-]*)\",[ \t]*([A-Za-z_][A-Za-z0-9_]*),[ \t]*\"(tests/contract/[A-Za-z0-9_./-]+[.]cpp)\",[ \t]*([A-Za-z][A-Za-z0-9_-]*),[ \t]*([^,() \t\"]+)\\)$")
      set(name "${CMAKE_MATCH_1}")
      set(symbol "${CMAKE_MATCH_2}")
      set(owner "${CMAKE_MATCH_3}")
      set(profile "${CMAKE_MATCH_4}")
      set(tags "${CMAKE_MATCH_5}")
    elseif(line MATCHES
       "^RUND_NODE_TEST_CASE\\(\"([A-Za-z0-9][A-Za-z0-9_.-]*)\",[ \t]*([A-Za-z_][A-Za-z0-9_]*),[ \t]*\"(tests/contract/[A-Za-z0-9_./-]+[.]cpp)\",[ \t]*([A-Za-z][A-Za-z0-9_-]*)\\)$")
      set(name "${CMAKE_MATCH_1}")
      set(symbol "${CMAKE_MATCH_2}")
      set(owner "${CMAKE_MATCH_3}")
      set(profile "${CMAKE_MATCH_4}")
    elseif(line MATCHES
       "^RUND_NODE_TEST_CASE\\(\"([A-Za-z0-9][A-Za-z0-9_.-]*)\",[ \t]*([A-Za-z_][A-Za-z0-9_]*),[ \t]*\"(tests/contract/[A-Za-z0-9_./-]+[.]cpp)\"\\)$")
      set(name "${CMAKE_MATCH_1}")
      set(symbol "${CMAKE_MATCH_2}")
      set(owner "${CMAKE_MATCH_3}")
    else()
      message(FATAL_ERROR "Malformed node test case in ${path}: ${line}")
    endif()
    rund_node_require_test_tags("${tags}")

    set(declared_owner "${owner}")
    string(REPLACE "/" ";" owner_parts "${declared_owner}")
    list(FIND owner_parts "." current_index)
    list(FIND owner_parts ".." parent_index)
    if(NOT current_index EQUAL -1 OR NOT parent_index EQUAL -1)
      message(FATAL_ERROR
        "Node test case owner must use a canonical path in ${path}: ${line}")
    endif()
    get_property(node_root GLOBAL PROPERTY RUND_NODE_TEST_ROOT)
    set(owner_path "${node_root}/${declared_owner}")
    if(NOT EXISTS "${owner_path}" OR IS_DIRECTORY "${owner_path}")
      message(FATAL_ERROR "Missing node test case owner: ${owner_path}")
    endif()
    file(REAL_PATH "${owner_path}" owner_path)
    file(RELATIVE_PATH owner "${node_root}" "${owner_path}")
    if(IS_ABSOLUTE "${owner}" OR owner MATCHES "^([.][.]/|[.][.]$)")
      message(FATAL_ERROR
        "Node test case owner escapes the Node source root: ${owner_path}")
    endif()
    if(NOT owner STREQUAL declared_owner)
      message(FATAL_ERROR
        "Node test case owner is not its canonical source path: ${declared_owner}")
    endif()

    list(FIND RUND_NODE_LINK_PROFILES "${profile}" profile_index)
    if(profile_index EQUAL -1)
      message(FATAL_ERROR
        "Unknown Node test link profile ${profile} in ${path}: ${line}")
    endif()
    set_property(GLOBAL APPEND PROPERTY
      RUND_NODE_TEST_CASE_NAMES "${name}")
    set_property(GLOBAL APPEND PROPERTY
      RUND_NODE_TEST_CASE_SYMBOLS "${symbol}")
    set_property(GLOBAL APPEND PROPERTY
      RUND_NODE_TEST_CASE_OWNERS "${owner}")
    set_property(GLOBAL APPEND PROPERTY
      RUND_NODE_TEST_CASE_GROUPS "${group}")
    set_property(GLOBAL APPEND PROPERTY
      RUND_NODE_TEST_CASE_SUITES "${suite}")
    set_property(GLOBAL APPEND PROPERTY
      RUND_NODE_TEST_CASE_LINK_PROFILES "${profile}")
    set_property(GLOBAL APPEND PROPERTY
      RUND_NODE_TEST_CASE_TAGS "${tags}")
  endforeach()
endfunction()

function(rund_node_registry_suites file)
  rund_node_registry_track("${file}")
  get_filename_component(dir "${file}" DIRECTORY)
  file(STRINGS "${file}" lines)
  set(suite_files)

  foreach(line IN LISTS lines)
    string(STRIP "${line}" line)
    if(line STREQUAL "" OR line MATCHES "^//")
      continue()
    endif()
    if(NOT line MATCHES
        "^RUND_NODE_TEST_SUITE\\(\"(cases/[A-Za-z0-9_./-]+\\.def)\",[ \t]*([A-Za-z][A-Za-z0-9_.-]*)\\)$")
      message(FATAL_ERROR "Malformed node test suite in ${file}: ${line}")
    endif()
    set(relative "${CMAKE_MATCH_1}")
    set(group "${CMAKE_MATCH_2}")
    string(REPLACE "/" ";" path_parts "${relative}")
    list(FIND path_parts ".." parent_index)
    if(NOT parent_index EQUAL -1)
      message(FATAL_ERROR "Node test suite must stay below cases/: ${line}")
    endif()
    get_filename_component(next "${dir}/${relative}" ABSOLUTE)
    if(NOT EXISTS "${next}" OR IS_DIRECTORY "${next}")
      message(FATAL_ERROR "Missing node test suite fragment: ${next}")
    endif()
    list(FIND suite_files "${next}" duplicate_suite)
    if(NOT duplicate_suite EQUAL -1)
      message(FATAL_ERROR "Duplicate node test suite fragment: ${next}")
    endif()
    list(APPEND suite_files "${next}")

    get_property(before GLOBAL PROPERTY RUND_NODE_TEST_CASE_NAMES)
    list(LENGTH before before_count)
    rund_node_registry_fragment("${next}" "${group}" "${next}")
    get_property(after GLOBAL PROPERTY RUND_NODE_TEST_CASE_NAMES)
    list(LENGTH after after_count)
    if(after_count EQUAL before_count)
      message(FATAL_ERROR "Node test suite ${relative} has no cases")
    endif()
  endforeach()
endfunction()

function(rund_node_registry_load file)
  if(NOT RUND_NODE_LINK_PROFILES)
    message(FATAL_ERROR "Node link profiles must be loaded before test cases")
  endif()
  if(NOT EXISTS "${file}" OR IS_DIRECTORY "${file}")
    message(FATAL_ERROR "Missing Node test registry: ${file}")
  endif()

  set_property(GLOBAL PROPERTY RUND_NODE_TEST_CASE_NAMES "")
  set_property(GLOBAL PROPERTY RUND_NODE_TEST_CASE_SYMBOLS "")
  set_property(GLOBAL PROPERTY RUND_NODE_TEST_CASE_OWNERS "")
  set_property(GLOBAL PROPERTY RUND_NODE_TEST_CASE_GROUPS "")
  set_property(GLOBAL PROPERTY RUND_NODE_TEST_CASE_SUITES "")
  set_property(GLOBAL PROPERTY RUND_NODE_TEST_CASE_LINK_PROFILES "")
  set_property(GLOBAL PROPERTY RUND_NODE_TEST_CASE_TAGS "")
  set_property(GLOBAL PROPERTY RUND_NODE_REGISTRY_INPUTS "")
  get_filename_component(registry_dir "${file}" DIRECTORY)
  get_filename_component(node_root "${registry_dir}/../.." ABSOLUTE)
  file(REAL_PATH "${node_root}" node_root)
  set_property(GLOBAL PROPERTY RUND_NODE_TEST_ROOT "${node_root}")
  rund_node_registry_suites("${file}")

  get_property(names GLOBAL PROPERTY RUND_NODE_TEST_CASE_NAMES)
  get_property(symbols GLOBAL PROPERTY RUND_NODE_TEST_CASE_SYMBOLS)
  get_property(owners GLOBAL PROPERTY RUND_NODE_TEST_CASE_OWNERS)
  get_property(groups GLOBAL PROPERTY RUND_NODE_TEST_CASE_GROUPS)
  get_property(suites GLOBAL PROPERTY RUND_NODE_TEST_CASE_SUITES)
  get_property(profiles GLOBAL PROPERTY RUND_NODE_TEST_CASE_LINK_PROFILES)
  get_property(tags GLOBAL PROPERTY RUND_NODE_TEST_CASE_TAGS)

  list(LENGTH names count)
  list(LENGTH symbols symbol_count)
  list(LENGTH owners owner_count)
  list(LENGTH groups group_count)
  list(LENGTH suites suite_count)
  list(LENGTH profiles profile_count)
  list(LENGTH tags tag_count)
  if(count EQUAL 0)
    message(FATAL_ERROR "No node test cases registered")
  endif()
  if(NOT count EQUAL symbol_count OR NOT count EQUAL owner_count OR
     NOT count EQUAL group_count OR
     NOT count EQUAL suite_count OR NOT count EQUAL profile_count OR
     NOT count EQUAL tag_count)
    message(FATAL_ERROR
      "Node test case names, symbols, owners, groups, suites, link profiles, and tags disagree")
  endif()

  set(unique_names ${names})
  list(REMOVE_DUPLICATES unique_names)
  list(LENGTH unique_names unique_name_count)
  if(NOT unique_name_count EQUAL count)
    message(FATAL_ERROR "Duplicate node test case name")
  endif()
  set(unique_symbols ${symbols})
  list(REMOVE_DUPLICATES unique_symbols)
  list(LENGTH unique_symbols unique_symbol_count)
  if(NOT unique_symbol_count EQUAL count)
    message(FATAL_ERROR "Duplicate node test case symbol")
  endif()

  set(NODE_TEST_CASES ${names} PARENT_SCOPE)
  set(NODE_TEST_CASE_SYMBOLS ${symbols} PARENT_SCOPE)
  set(NODE_TEST_CASE_OWNERS ${owners} PARENT_SCOPE)
  set(NODE_TEST_CASE_GROUPS ${groups} PARENT_SCOPE)
  set(NODE_TEST_CASE_SUITES ${suites} PARENT_SCOPE)
  set(NODE_TEST_CASE_LINK_PROFILES ${profiles} PARENT_SCOPE)
  set(NODE_TEST_CASE_TAGS ${tags} PARENT_SCOPE)
endfunction()

function(rund_node_registry_case_has_tag out name tag)
  rund_node_require_test_tag("${tag}")
  list(FIND NODE_TEST_CASES "${name}" case_index)
  if(case_index EQUAL -1)
    message(FATAL_ERROR "Unknown Node test case: ${name}")
  endif()
  list(GET NODE_TEST_CASE_TAGS ${case_index} tags)
  string(REPLACE "+" ";" tags "${tags}")
  list(FIND tags "${tag}" tag_index)
  if(tag_index EQUAL -1)
    set(${out} FALSE PARENT_SCOPE)
  else()
    set(${out} TRUE PARENT_SCOPE)
  endif()
endfunction()
