list(APPEND NODE_SOURCES
  src/compute/backend/accel.cpp
  src/compute/backend/accel/transfer.cpp
  src/compute/backend/accel/program.cpp
  src/compute/backend/accel/pipeline/memory.cpp
  src/compute/backend/accel/pipeline/preparation.cpp
  src/compute/backend/accel/pipeline/submission.cpp
  src/compute/backend/accel/pipeline/window.cpp
  src/compute/backend/accel/pipeline/schedule.cpp
  src/compute/backend/accel/pipeline/sliding.cpp
  src/compute/backend/accel/buffer.cpp
  src/compute/backend/accel/residency.cpp
  src/compute/backend/accel/transfer/download.cpp
  src/compute/backend/accel/transfer/prepare.cpp
  src/compute/backend/accel/transfer/upload.cpp
  src/compute/backend/accel/execution/service_free_direct/completion.cpp
  src/compute/backend/accel/execution/service_free_direct/publication.cpp
  src/compute/backend/accel/execution/service_free_direct/run.cpp
  src/compute/backend/accel/execution/service_free_direct/submission.cpp
  src/compute/device/residency/execution/direct_recurrence/accept/registration.cpp
  src/compute/device/residency/execution/direct_recurrence/accept/validation.cpp
  src/compute/device/residency/execution/direct_recurrence/accept/final.cpp
  src/compute/device/residency/execution/direct_recurrence/begin.cpp
  src/compute/device/residency/execution/direct_recurrence/prepare.cpp
  src/compute/device/residency/execution/direct_recurrence/abort.cpp
  src/compute/device/residency/execution/direct_recurrence/registration.cpp
  src/compute/device/residency/execution/device_vsm/registration.cpp
  src/compute/device/residency/execution/sliding/bind.cpp
  src/compute/device/residency/execution/sliding/accept.cpp
  src/compute/device/residency/execution/sliding/final/frames.cpp
  src/compute/device/residency/execution/sliding/final/abort.cpp
  src/compute/device/residency/execution/sliding/final/prepare.cpp
  src/compute/device/residency/execution/sliding/final/raw.cpp
  src/compute/device/residency/execution/sliding/final/fused.cpp
  src/compute/device/residency/execution/sliding/failure.cpp
  src/compute/device/residency/execution/sliding/final.cpp
  src/compute/device/residency/execution/sliding/invalidation.cpp
  src/compute/device/residency/execution/sliding/invocation.cpp
  src/compute/device/residency/execution/sliding/invocation/capacity.cpp
  src/compute/device/residency/execution/sliding/invocation/fetch_persist.cpp
  src/compute/device/residency/execution/sliding/invocation/predecessor.cpp
  src/compute/device/residency/execution/sliding/invocation/projection.cpp
  src/compute/device/residency/execution/sliding/lifecycle.cpp
  src/compute/device/residency/execution/sliding/logical_drain.cpp
  src/compute/device/residency/execution/sliding/logical_fetch.cpp
  src/compute/device/residency/execution/sliding/logical_native.cpp
  src/compute/device/residency/execution/sliding/logical_persist.cpp
  src/compute/device/residency/execution/sliding/logical_promote.cpp
  src/compute/device/residency/execution/sliding/owner.cpp
  src/compute/device/residency/execution/sliding/physical/drain/issue.cpp
  src/compute/device/residency/execution/sliding/physical/drain/release.cpp
  src/compute/device/residency/execution/sliding/physical/drain/terminal.cpp
  src/compute/device/residency/execution/sliding/physical/fetch/issue.cpp
  src/compute/device/residency/execution/sliding/physical/fetch/release.cpp
  src/compute/device/residency/execution/sliding/physical/fetch/terminal.cpp
  src/compute/device/residency/execution/sliding/physical/native/issue.cpp
  src/compute/device/residency/execution/sliding/physical/native/release.cpp
  src/compute/device/residency/execution/sliding/physical/native/terminal.cpp
  src/compute/device/residency/execution/sliding/physical/persist/issue.cpp
  src/compute/device/residency/execution/sliding/physical/persist/release.cpp
  src/compute/device/residency/execution/sliding/physical/persist/terminal.cpp
  src/compute/device/residency/execution/sliding/physical/promote/issue.cpp
  src/compute/device/residency/execution/sliding/physical/promote/release.cpp
  src/compute/device/residency/execution/sliding/physical/promote/terminal.cpp
  src/compute/device/residency/execution/sliding/quarantine_coordinate.cpp
  src/compute/device/residency/execution/sliding/reject.cpp
  src/compute/device/residency/execution/sliding/reject_coordinate.cpp
  src/compute/device/residency/execution/sliding/state.cpp
  src/compute/batch/run.cpp
  src/compute/job/accel.cpp
  src/compute/open/accel.cpp
  src/compute/virtual/run/device_vsm/admission.cpp
  src/compute/virtual/run/device_vsm/admission/shape.cpp
  src/compute/virtual/run/device_vsm/admission/pipeline.cpp
  src/compute/virtual/run/device_vsm/admission/validate.cpp
  src/compute/virtual/run/device_vsm/admission/owner.cpp
  src/compute/virtual/run/device_vsm/evidence/backing.cpp
  src/compute/virtual/run/device_vsm/evidence/run.cpp
  src/compute/virtual/run/device_vsm/execute.cpp
  src/compute/virtual/run/device_vsm/final/close.cpp
  src/compute/virtual/run/device_vsm/final/publication.cpp
  src/compute/virtual/run/device_vsm/final/statistics.cpp
  src/compute/virtual/run/device_vsm/pipeline/begin.cpp
  src/compute/virtual/run/device_vsm/pipeline/snapshot.cpp
  src/compute/virtual/run/device_vsm/prepare.cpp
  src/compute/virtual/run/device_vsm/prepare/buffers.cpp
  src/compute/virtual/run/device_vsm/prepare/buffers/graph.cpp
  src/compute/virtual/run/device_vsm/prepare/buffers/match.cpp
  src/compute/virtual/run/device_vsm/prepare/cold.cpp
  src/compute/virtual/run/device_vsm/prepare/graph_wavefront/dependency.cpp
  src/compute/virtual/run/device_vsm/prepare/graph_wavefront/page_map.cpp
  src/compute/virtual/run/device_vsm/prepare/graph_wavefront/resident.cpp
  src/compute/virtual/run/device_vsm/prepare/graph_wavefront/validation.cpp
  src/compute/virtual/run/device_vsm/prepare/graph_wavefront/resources.cpp
  src/compute/virtual/run/device_vsm/prepare/graph_wavefront/owners.cpp
  src/compute/virtual/run/device_vsm/prepare/graph_wavefront/stages.cpp
  src/compute/virtual/run/device_vsm/prepare/graph_pointwise_topology.cpp
  src/compute/virtual/run/device_vsm/prepare/memory.cpp
  src/compute/virtual/run/device_vsm/prepare/warm.cpp
  src/compute/virtual/run/device_vsm/prepare/warm/identity.cpp
  src/compute/virtual/run/device_vsm/prepare/warm/pipeline.cpp
  src/compute/virtual/run/device_vsm/prepare/warm/pointwise.cpp
  src/compute/virtual/run/device_vsm/prepare/warm/resident.cpp
  src/compute/virtual/run/device_vsm/prepare/warm/wavefront.cpp
  src/compute/virtual/run/device_vsm/staging/hash.cpp
  src/compute/virtual/run/device_vsm/staging/input.cpp
  src/compute/virtual/run/device_vsm/staging/output.cpp
  src/compute/virtual/run/device_vsm/submission.cpp
  src/compute/virtual/run/device_vsm/submission/fallback.cpp
  src/compute/virtual/run/sliding/drain.cpp
  src/compute/virtual/run/sliding/drain/copy.cpp
  src/compute/virtual/run/sliding/execute.cpp
  src/compute/virtual/run/sliding/execute/bind.cpp
  src/compute/virtual/run/sliding/execute/owner.cpp
  src/compute/virtual/run/sliding/execute/reject.cpp
  src/compute/virtual/run/sliding/execute/state.cpp
  src/compute/virtual/run/sliding/fetch.cpp
  src/compute/virtual/run/sliding/fetch/batch/io.cpp
  src/compute/virtual/run/sliding/fetch/batch/issue.cpp
  src/compute/virtual/run/sliding/fetch/batch/retire.cpp
  src/compute/virtual/run/sliding/fetch/fill.cpp
  src/compute/virtual/run/sliding/fetch/reuse.cpp
  src/compute/virtual/run/sliding/fetch/telemetry.cpp
  src/compute/virtual/run/sliding/final/close.cpp
  src/compute/virtual/run/sliding/final/completion.cpp
  src/compute/virtual/run/sliding/final/quarantine.cpp
  src/compute/virtual/run/sliding/final/statistics.cpp
  src/compute/virtual/run/sliding/final/status.cpp
  src/compute/virtual/run/sliding/native.cpp
  src/compute/virtual/run/sliding/output.cpp
  src/compute/virtual/run/sliding/pipeline/begin.cpp
  src/compute/virtual/run/sliding/pipeline/finish.cpp
  src/compute/virtual/run/sliding/pipeline/injection.cpp
  src/compute/virtual/run/sliding/pipeline/rebase.cpp
  src/compute/virtual/run/sliding/persist.cpp
  src/compute/virtual/run/sliding/persist/io.cpp
  src/compute/virtual/run/sliding/persist/recovery.cpp
  src/compute/virtual/run/sliding/persist/telemetry.cpp
  src/compute/virtual/run/sliding/persistent/completion.cpp
  src/compute/virtual/run/sliding/persistent/final.cpp
  src/compute/virtual/run/sliding/persistent/memory.cpp
  src/compute/virtual/run/sliding/persistent/prepare.cpp
  src/compute/virtual/run/sliding/persistent/publication.cpp
  src/compute/virtual/run/sliding/persistent/request.cpp
  src/compute/virtual/run/sliding/persistent/service.cpp
  src/compute/virtual/run/sliding/persistent/service/admission.cpp
  src/compute/virtual/run/sliding/persistent/service/coordinate.cpp
  src/compute/virtual/run/sliding/persistent/service/exchange.cpp
  src/compute/virtual/run/sliding/persistent/service/failure.cpp
  src/compute/virtual/run/sliding/persistent/service/injection.cpp
  src/compute/virtual/run/sliding/persistent/service/injection_failure.cpp
  src/compute/virtual/run/sliding/persistent/service/native.cpp
  src/compute/virtual/run/sliding/persistent/service/outcome.cpp
  src/compute/virtual/run/sliding/persistent/service/output.cpp
  src/compute/virtual/run/sliding/persistent/service/selection.cpp
  src/compute/virtual/run/sliding/persistent/service/setup.cpp
  src/compute/virtual/run/sliding/persistent/service/suffix.cpp
  src/compute/virtual/run/sliding/persistent/statistics.cpp
  src/compute/virtual/run/sliding/persistent/submit.cpp
  src/compute/virtual/run/sliding/prepare.cpp
  src/compute/virtual/run/sliding/prepare/admission.cpp
  src/compute/virtual/run/sliding/prepare/backend.cpp
  src/compute/virtual/run/sliding/prepare/owner.cpp
  src/compute/virtual/run/sliding/prepare/roles.cpp
  src/compute/virtual/run/sliding/promote.cpp
  src/compute/virtual/run/sliding/promote/assemble.cpp
  src/compute/virtual/run/sliding/promote/copy.cpp
  src/compute/virtual/run/sliding/projection.cpp
  src/compute/virtual/run/sliding/state.cpp
)

if(RUND_TEST_NODE)
  set_source_files_properties(src/compute/open/accel.cpp PROPERTIES
    COMPILE_DEFINITIONS RUND_NODE_OPEN_PROBE=1)
endif()
