cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED ROOT OR ROOT STREQUAL "")
  message(FATAL_ERROR "ROOT is required")
endif()
set(query_modes 0)
if(LIST_CASES)
  math(EXPR query_modes "${query_modes} + 1")
endif()
if(DEFINED NAME AND NOT NAME STREQUAL "")
  math(EXPR query_modes "${query_modes} + 1")
endif()
if(DEFINED TAG AND NOT TAG STREQUAL "")
  math(EXPR query_modes "${query_modes} + 1")
endif()
if(CATALOG)
  math(EXPR query_modes "${query_modes} + 1")
endif()
if(NOT query_modes EQUAL 1)
  message(FATAL_ERROR
    "exactly one of NAME, TAG, LIST_CASES, or CATALOG is required")
endif()
get_filename_component(ROOT "${ROOT}" ABSOLUTE)
if(NOT DEFINED BACKEND)
  set(BACKEND "")
endif()
if((LIST_CASES OR DEFINED TAG OR CATALOG) AND NOT BACKEND STREQUAL "")
  message(FATAL_ERROR
    "Case listing, tag selection, and catalog generation do not accept a backend selector")
endif()

# A regex is not an exact-case lookup.  Return no row without weakening the
# parser used for valid registry names.
if(DEFINED NAME AND NOT NAME MATCHES "^[A-Za-z0-9][A-Za-z0-9_.-]*$")
  return()
endif()
include("${ROOT}/node/cmake/node/profiles.cmake")
include("${ROOT}/node/cmake/tests/registry.cmake")
include("${ROOT}/node/cmake/node/contract/routes.cmake")
if(DEFINED TAG)
  rund_node_test_tag_valid(valid_tag "${TAG}")
  if(NOT valid_tag)
    return()
  endif()
endif()
rund_node_registry_load("${ROOT}/node/tests/contract/cases.def")

if(CATALOG)
  function(catalog_inputs out_rows out_identity)
    get_property(inputs GLOBAL PROPERTY RUND_NODE_REGISTRY_INPUTS)
    list(APPEND inputs
      "${ROOT}/node/cmake/node/profiles.cmake"
      "${ROOT}/node/cmake/node/contract/routes.cmake"
      "${ROOT}/node/cmake/tests/registry.cmake"
      "${ROOT}/tools/internal/case/query.cmake"
      "${ROOT}/tools/internal/case/catalog")
    list(REMOVE_DUPLICATES inputs)
    list(SORT inputs)
    set(rows)
    set(identity)
    foreach(input IN LISTS inputs)
      if(NOT EXISTS "${input}" OR IS_DIRECTORY "${input}")
        message(FATAL_ERROR "Missing case catalog input: ${input}")
      endif()
      file(REAL_PATH "${input}" canonical)
      file(RELATIVE_PATH relative "${ROOT}" "${canonical}")
      if(IS_ABSOLUTE "${relative}" OR
         relative MATCHES "^([.][.]/|[.][.]$)" OR
         NOT relative MATCHES "^[A-Za-z0-9_./-]+$")
        message(FATAL_ERROR
          "Case catalog input escapes the repository: ${input}")
      endif()
      file(SHA256 "${canonical}" hash)
      list(APPEND rows "input\t${hash}\t${relative}")
      string(APPEND identity "${hash}\t${relative}\n")
    endforeach()
    set(${out_rows} "${rows}" PARENT_SCOPE)
    set(${out_identity} "${identity}" PARENT_SCOPE)
  endfunction()

  # The cache generator parses twice around a complete input identity.  If an
  # owning registry, route, profile, or parser file changes during generation,
  # the two identities differ and no mixed catalog can be published.
  catalog_inputs(first_inputs first_identity)
  rund_node_registry_load("${ROOT}/node/tests/contract/cases.def")
  catalog_inputs(second_inputs second_identity)
  if(NOT first_identity STREQUAL second_identity)
    message(FATAL_ERROR "Case catalog inputs changed during canonical parsing")
  endif()

  set(body "catalog\n")
  foreach(row IN LISTS second_inputs)
    string(APPEND body "${row}\n")
  endforeach()
  list(LENGTH NODE_TEST_CASES case_count)
  math(EXPR last_case "${case_count} - 1")
  foreach(case_index RANGE 0 ${last_case})
    list(GET NODE_TEST_CASES ${case_index} name)
    list(GET NODE_TEST_CASE_TAGS ${case_index} tags)
    list(GET NODE_TEST_CASE_OWNERS ${case_index} owner)
    rund_node_case_route(target resource profile "${name}" "")
    rund_node_focus_anchor(anchor "${name}" "")
    string(APPEND body
      "case\t${name}\t${target}\t${resource}\t${profile}\t${tags}\t${owner}\t${anchor}\n")
    rund_node_registry_case_has_tag(supports_backend "${name}" backend)
    if(supports_backend)
      rund_node_case_route(
        cpu_target cpu_resource cpu_profile "${name}" cpu)
      rund_node_focus_anchor(cpu_anchor "${name}" cpu)
      string(APPEND body
        "cpu\t${name}\t${cpu_target}\t${cpu_resource}\t${cpu_profile}\t${cpu_anchor}\n")
    endif()
  endforeach()
  string(SHA256 seal "${body}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E echo
    "${body}seal\t${seal}")
  return()
endif()

if(LIST_CASES)
  set(rows)
  list(LENGTH NODE_TEST_CASES case_count)
  math(EXPR last_case "${case_count} - 1")
  foreach(case_index RANGE 0 ${last_case})
    list(GET NODE_TEST_CASES ${case_index} name)
    rund_node_case_route(target resource profile "${name}" "")
    list(APPEND rows "${name}\t${target}\t${resource}\t${profile}")
  endforeach()
  list(JOIN rows "\n" output)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${output}")
  return()
endif()

if(DEFINED TAG)
  set(rows)
  list(LENGTH NODE_TEST_CASES case_count)
  math(EXPR last_case "${case_count} - 1")
  foreach(case_index RANGE 0 ${last_case})
    list(GET NODE_TEST_CASES ${case_index} name)
    rund_node_registry_case_has_tag(matches "${name}" "${TAG}")
    if(matches)
      rund_node_case_route(target resource profile "${name}" "")
      list(APPEND rows "${name}\t${target}\t${resource}\t${profile}")
    endif()
  endforeach()
  if(rows)
    list(JOIN rows "\n" output)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${output}")
  endif()
  return()
endif()

list(FIND NODE_TEST_CASES "${NAME}" case_index)
if(case_index EQUAL -1)
  return()
endif()
rund_node_case_route(target resource profile "${NAME}" "${BACKEND}")

execute_process(COMMAND "${CMAKE_COMMAND}" -E echo
  "${NAME}\t${target}\t${resource}\t${profile}")
