cmake_policy(PUSH)
cmake_policy(SET CMP0054 NEW)

function(rund_read_sdk_surface registry direct_out private_file_out
         private_tree_out)
  if(NOT EXISTS "${registry}" OR IS_DIRECTORY "${registry}")
    message(FATAL_ERROR "SDK header surface registry is unavailable: ${registry}")
  endif()

  file(STRINGS "${registry}" rows)
  if(NOT rows)
    message(FATAL_ERROR "SDK header surface registry is empty: ${registry}")
  endif()
  list(POP_FRONT rows header)
  if(NOT header STREQUAL "kind\tpath")
    message(FATAL_ERROR "SDK header surface registry has an invalid header")
  endif()

  set(sorted "${rows}")
  list(SORT sorted)
  if(NOT "${rows}" STREQUAL "${sorted}")
    message(FATAL_ERROR "SDK header surface registry must be sorted")
  endif()

  set(direct)
  set(private_files)
  set(private_trees)
  set(paths)
  foreach(row IN LISTS rows)
    string(REPLACE "\t" ";" fields "${row}")
    list(LENGTH fields field_count)
    if(NOT field_count EQUAL 2)
      message(FATAL_ERROR "SDK header surface row is malformed: ${row}")
    endif()
    list(GET fields 0 kind)
    list(GET fields 1 path)
    if(path STREQUAL "" OR path MATCHES "^/" OR path MATCHES "\\\\" OR
       path MATCHES "(^|/)\\.\\.?(/|$)" OR
       NOT path MATCHES "^[A-Za-z0-9._/-]+$")
      message(FATAL_ERROR "SDK header surface path is invalid: ${path}")
    endif()
    list(FIND paths "${path}" duplicate_index)
    if(NOT duplicate_index EQUAL -1)
      message(FATAL_ERROR "SDK header surface path is duplicated: ${path}")
    endif()
    list(APPEND paths "${path}")

    if(kind STREQUAL "direct")
      if(NOT path MATCHES "\\.hpp$")
        message(FATAL_ERROR "SDK direct entry is not a header: ${path}")
      endif()
      list(APPEND direct "${path}")
    elseif(kind STREQUAL "private-file")
      list(APPEND private_files "${path}")
    elseif(kind STREQUAL "private-tree")
      list(APPEND private_trees "${path}")
    else()
      message(FATAL_ERROR "SDK header surface kind is invalid: ${kind}")
    endif()
  endforeach()

  if(NOT direct OR NOT private_files OR NOT private_trees)
    message(FATAL_ERROR "SDK header surface registry is incomplete")
  endif()
  set(${direct_out} "${direct}" PARENT_SCOPE)
  set(${private_file_out} "${private_files}" PARENT_SCOPE)
  set(${private_tree_out} "${private_trees}" PARENT_SCOPE)
endfunction()

function(rund_check_sdk_closure inventory_var direct_var private_file_var
         private_tree_var)
  foreach(header IN LISTS ${direct_var})
    list(FIND ${inventory_var} "${header}" direct_index)
    if(direct_index EQUAL -1)
      message(FATAL_ERROR "SDK header closure omits direct entry: ${header}")
    endif()
  endforeach()

  foreach(path IN LISTS ${inventory_var})
    foreach(private_file IN LISTS ${private_file_var})
      if("${path}" STREQUAL "${private_file}")
        message(FATAL_ERROR "SDK header closure reaches private file: ${path}")
      endif()
    endforeach()
    foreach(private_tree IN LISTS ${private_tree_var})
      string(FIND "${path}/" "${private_tree}/" private_tree_position)
      if(private_tree_position EQUAL 0)
        message(FATAL_ERROR "SDK header closure reaches private tree: ${path}")
      endif()
    endforeach()
  endforeach()
endfunction()

function(rund_read_sdk_inventory manifest output_var)
  if(NOT EXISTS "${manifest}" OR IS_DIRECTORY "${manifest}")
    message(FATAL_ERROR "installed SDK header inventory is unavailable: ${manifest}")
  endif()

  file(STRINGS "${manifest}" rows)
  if(NOT rows)
    message(FATAL_ERROR "installed SDK header inventory is empty: ${manifest}")
  endif()
  list(POP_FRONT rows header)
  if(NOT header STREQUAL "path")
    message(FATAL_ERROR "installed SDK header inventory has an invalid header")
  endif()

  set(sorted "${rows}")
  list(SORT sorted)
  list(REMOVE_DUPLICATES sorted)
  if(NOT "${rows}" STREQUAL "${sorted}")
    message(FATAL_ERROR
      "installed SDK header inventory must be sorted and unique")
  endif()
  foreach(path IN LISTS rows)
    if(path STREQUAL "" OR path MATCHES "^/" OR path MATCHES "\\\\" OR
       path MATCHES "(^|/)\\.\\.?(/|$)" OR
       NOT path MATCHES "^[A-Za-z0-9._/-]+$")
      message(FATAL_ERROR "installed SDK header path is invalid: ${path}")
    endif()
  endforeach()
  set(${output_var} "${rows}" PARENT_SCOPE)
endfunction()

cmake_policy(POP)
