#pragma once

#include <math32/core/model.hpp>
#include <math32/simd/model.hpp>
#include <math32/simd/memory.hpp>
#include <math32/simd/select.hpp>
#include <math32/simd/mask.hpp>
#include <math32/simd/compare.hpp>
#include <math32/simd/arithmetic.hpp>
#include <math32/simd/reduction.hpp>
#include <math32/fixed/constants.hpp>
#include <math32/fixed/arithmetic.hpp>
#include <math32/fixed/sqrt.hpp>
#include <math32/nonlinear/exp.hpp>
#include <math32/nonlinear/log.hpp>
#include <math32/turn/constants.hpp>
#include <math32/turn/trig.hpp>
#include <math32/turn/atan.hpp>
#include <math32/stat/mean.hpp>
#include <math32/stat/variance.hpp>
#include <math32/stat/rms.hpp>
#include <math32/stat/interpolation.hpp>
#include <math32/geom/vec2x.hpp>
#include <math32/geom/vec3x.hpp>
#include <math32/geom/view.hpp>
#include <math32/geom/vector.hpp>
#include <math32/soa/status.hpp>
#include <math32/soa/validate.hpp>
#include <math32/soa/span.hpp>
#include <math32/soa/geom.hpp>
#include <math32/quant/clamp.hpp>
#include <math32/quant/requant.hpp>
#include <math32/nn/model.hpp>
#include <math32/nn/dot.hpp>
#include <math32/nn/activation.hpp>
#include <math32/nn/norm.hpp>
#include <math32/nn/rope.hpp>
#include <math32/prob/model.hpp>
#include <math32/prob/max.hpp>
#include <math32/prob/logsumexp.hpp>
#include <math32/prob/softmax.hpp>
#include <math32/prob/logsoftmax.hpp>
#include <math32/prob/softplus.hpp>
#include <math32/prob/logsigmoid.hpp>
#include <math32/prob/entropy/cross.hpp>
#include <math32/rl/recurrence.hpp>
