list(APPEND NODE_SOURCES
  src/accel/backend/buffer.cpp
  src/accel/backend/catalog.cpp
  src/accel/backend/match.cpp
  src/accel/backend/resource.cpp
  src/accel/backend/token.cpp
  src/accel/buffer/create.cpp
  src/accel/buffer/resident.cpp
  src/accel/buffer/stats.cpp
  src/accel/buffer/memory.cpp
  src/accel/buffer/transfer.cpp
  src/accel/compact/shape.cpp
  src/accel/factor/shape.cpp
  src/accel/gather/shape.cpp
  src/accel/histogram/shape.cpp
  src/accel/matrix/shape.cpp
  src/accel/graph.cpp
  src/accel/graph/admission.cpp
  src/accel/graph/admission/validation.cpp
  src/accel/graph/admission/compact.cpp
  src/accel/graph/admission/factor.cpp
  src/accel/graph/admission/gather.cpp
  src/accel/graph/admission/histogram.cpp
  src/accel/graph/admission/matrix.cpp
  src/accel/graph/admission/map.cpp
  src/accel/graph/admission/partition.cpp
  src/accel/graph/admission/reduce.cpp
  src/accel/graph/admission/scan.cpp
  src/accel/graph/admission/segmented.cpp
  src/accel/graph/admission/segmented/reduce.cpp
  src/accel/graph/admission/scatter.cpp
  src/accel/graph/admission/solve.cpp
  src/accel/graph/admission/sort.cpp
  src/accel/graph/admission/spectrum.cpp
  src/accel/graph/admission/stencil.cpp
  src/accel/graph/admission/transform.cpp
  src/accel/graph/compile/append.cpp
  src/accel/graph/compile/base.cpp
  src/accel/graph/compile/buffers.cpp
  src/accel/graph/compile/node.cpp
  src/accel/graph/compile/state.cpp
  src/accel/graph/collective/bindings/compact.cpp
  src/accel/graph/collective/bindings/factor.cpp
  src/accel/graph/collective/bindings/gather.cpp
  src/accel/graph/collective/bindings/histogram.cpp
  src/accel/graph/collective/bindings/matrix.cpp
  src/accel/graph/collective/bindings/partition.cpp
  src/accel/graph/collective/bindings/reduce.cpp
  src/accel/graph/collective/bindings/scan.cpp
  src/accel/graph/collective/bindings/segmented.cpp
  src/accel/graph/collective/bindings/segmented/reduce.cpp
  src/accel/graph/collective/bindings/scatter.cpp
  src/accel/graph/collective/bindings/signature.cpp
  src/accel/graph/collective/bindings/solve.cpp
  src/accel/graph/collective/bindings/sort.cpp
  src/accel/graph/collective/bindings/spectrum.cpp
  src/accel/graph/collective/bindings/stencil.cpp
  src/accel/graph/collective/bindings/transform.cpp
  src/accel/graph/collective/defaults.cpp
  src/accel/graph/collective/desc.cpp
  src/accel/graph/collective/kind.cpp
  src/accel/graph/fusion.cpp
  src/accel/graph/fusion/bindings.cpp
  src/accel/graph/fusion/plan.cpp
  src/accel/graph/fusion/policy.cpp
  src/accel/graph/step.cpp
  src/accel/graph/token/admission.cpp
  src/accel/graph/token/reject.cpp
  src/accel/graph/token/mint.cpp
  src/accel/graph/token/reset.cpp
  src/accel/graph/token/capability.cpp
  src/accel/plan/validation/binding.cpp
  src/accel/plan/validation/binding/mode.cpp
  src/accel/plan/validation/caps.cpp
  src/accel/plan/validation/header.cpp
  src/accel/partition/shape.cpp
  src/accel/kernel.cpp
  src/accel/kernel/backend/run.cpp
  src/accel/kernel/bindings/source.cpp
  src/accel/kernel/bindings/compact.cpp
  src/accel/kernel/bindings/factor.cpp
  src/accel/kernel/bindings/gather.cpp
  src/accel/kernel/bindings/histogram.cpp
  src/accel/kernel/bindings/matrix.cpp
  src/accel/kernel/bindings/partition.cpp
  src/accel/kernel/bindings/reduce.cpp
  src/accel/kernel/bindings/scan.cpp
  src/accel/kernel/bindings/segmented.cpp
  src/accel/kernel/bindings/segmented/reduce.cpp
  src/accel/kernel/bindings/scatter.cpp
  src/accel/kernel/bindings/solve.cpp
  src/accel/kernel/bindings/sort.cpp
  src/accel/kernel/bindings/spectrum.cpp
  src/accel/kernel/bindings/stencil.cpp
  src/accel/kernel/bindings/step.cpp
  src/accel/kernel/bindings/transform.cpp
  src/accel/kernel/evidence.cpp
  src/accel/kernel/execute.cpp
  src/accel/kernel/fault.cpp
  src/accel/kernel/plan/compute.cpp
  src/accel/kernel/plan/step.cpp
  src/accel/kernel/prepared/batch.cpp
  src/accel/kernel/prepared/completion.cpp
  src/accel/kernel/prepared/evidence.cpp
  src/accel/kernel/prepared/pipeline.cpp
  src/accel/kernel/prepared/run.cpp
  src/accel/kernel/scratch.cpp
  src/accel/kernel/recurrence/build.cpp
  src/accel/kernel/recurrence/aggregate.cpp
  src/accel/kernel/recurrence/match.cpp
  src/accel/kernel/recurrence/plan.cpp
  src/accel/kernel/recurrence/source.cpp
  src/accel/kernel/reset/overlap.cpp
  src/accel/kernel/reset/proof.cpp
  src/accel/kernel/roundtrip/check.cpp
  src/accel/kernel/roundtrip/count.cpp
  src/accel/kernel/roundtrip/match.cpp
  src/accel/kernel/run/bindings.cpp
  src/accel/kernel/schedule/order.cpp
  src/accel/kernel/step/map/bindings.cpp
  src/accel/kernel/step/map/metadata.cpp
  src/accel/kernel/step/map/cpu.cpp
  src/accel/reduce/shape.cpp
  src/accel/resident/validation.cpp
  src/accel/scan/shape.cpp
  src/accel/segmented/reduce/shape.cpp
  src/accel/segmented/reduce/model.cpp
  src/accel/scatter/shape.cpp
  src/accel/segmented/shape.cpp
  src/accel/sort/shape.cpp
  src/accel/solve/shape.cpp
  src/accel/spectrum/shape.cpp
  src/accel/stencil/shape.cpp
  src/accel/transform/shape.cpp
)
