list(APPEND NODE_SOURCES
  src/accel/cpu/buffer.cpp
  src/accel/cpu/buffer/batch.cpp
  src/accel/cpu/compact.cpp
  src/accel/cpu/execute.cpp
  src/accel/cpu/factor.cpp
  src/accel/cpu/gather.cpp
  src/accel/cpu/histogram.cpp
  src/accel/cpu/kernel/run.cpp
  src/accel/cpu/lookup.cpp
  src/accel/cpu/matrix.cpp
  src/accel/cpu/ops.cpp
  src/accel/cpu/partition.cpp
  src/accel/cpu/pick.cpp
  src/accel/cpu/reduce.cpp
  src/accel/cpu/scan.cpp
  src/accel/cpu/scatter.cpp
  src/accel/cpu/segmented.cpp
  src/accel/cpu/segmented/reduce.cpp
  src/accel/cpu/solve.cpp
  src/accel/cpu/sort.cpp
  src/accel/cpu/spectrum.cpp
  src/accel/cpu/stats.cpp
  src/accel/cpu/stencil.cpp
  src/accel/cpu/transfer.cpp
  src/accel/cpu/transform.cpp
  src/accel/cpu/window.cpp
)
