list(APPEND NODE_SOURCES
  src/accel/metal/adapter/lifecycle.cpp
  src/accel/metal/buffer/access.mm
  src/accel/metal/buffer/ownership.cpp
  src/accel/metal/buffer/pool.mm
  src/accel/metal/buffer/resident/batch.cpp
  src/accel/metal/buffer/resident/create.mm
  src/accel/metal/buffer/resident/download.mm
  src/accel/metal/buffer/resident/lookup.mm
  src/accel/metal/buffer/resident/upload.mm
  src/accel/metal/buffer/stats.cpp
  src/accel/metal/pick.mm
  src/accel/metal/command/submit.mm
  src/accel/metal/compact/execute.mm
  src/accel/metal/compact/finish.mm
  src/accel/metal/compact/source.cpp
  src/accel/metal/gather/execute.mm
  src/accel/metal/gather/finish.mm
  src/accel/metal/gather/source.cpp
  src/accel/metal/histogram/encode.mm
  src/accel/metal/histogram/execute.mm
  src/accel/metal/histogram/finish.mm
  src/accel/metal/histogram/pipeline.mm
  src/accel/metal/histogram/resources.mm
  src/accel/metal/histogram/source.cpp
  src/accel/metal/object.mm
  src/accel/metal/partition/execute.mm
  src/accel/metal/partition/finish.mm
  src/accel/metal/partition/source.cpp
  src/accel/metal/pipeline.mm
  src/accel/metal/pipeline/cache.cpp
  src/accel/metal/kernel/prepared.mm
  src/accel/metal/scratch.mm
  src/accel/metal/kernel/batch.mm
  src/accel/metal/kernel/batch/copy.mm
  src/accel/metal/kernel/batch/encode.mm
  src/accel/metal/kernel/batch/plan.mm
  src/accel/metal/kernel/pipeline/capture.mm
  src/accel/metal/kernel/pipeline/prepare.mm
  src/accel/metal/kernel/pipeline/run.mm
  src/accel/metal/kernel/pipeline/source.cpp
  src/accel/metal/kernel/pipeline/status.mm
  src/accel/metal/kernel/pipeline/stub.cpp
  src/accel/metal/kernel/pipeline/aggregate/admit.mm
  src/accel/metal/kernel/pipeline/aggregate/prepare.mm
  src/accel/metal/kernel/pipeline/aggregate/source.cpp
  src/accel/metal/kernel/pipeline/prepare/admit.mm
  src/accel/metal/kernel/pipeline/prepare/allocate.mm
  src/accel/metal/kernel/pipeline/prepare/capture.mm
  src/accel/metal/kernel/pipeline/prepare/describe.mm
  src/accel/metal/kernel/pipeline/prepare/finalize.mm
  src/accel/metal/kernel/pipeline/prepare/program.mm
  src/accel/metal/kernel/pipeline/prepare/telemetry.mm
  src/accel/metal/kernel/pipeline/source/status.cpp
  src/accel/metal/kernel/pipeline/source/telemetry.cpp
  src/accel/metal/kernel/context.mm
  src/accel/metal/kernel/encode.mm
  src/accel/metal/kernel/finish.mm
  src/accel/metal/kernel/prepare.mm
  src/accel/metal/kernel/run.mm
  src/accel/metal/kernel/view.mm
  src/accel/metal/numeric/source.cpp
  src/accel/metal/numeric/32/source.cpp
  src/accel/metal/numeric/resource.mm
  src/accel/metal/numeric/prepare/factor.mm
  src/accel/metal/numeric/prepare/matrix.mm
  src/accel/metal/numeric/prepare/solve.mm
  src/accel/metal/numeric/prepare/spectrum.mm
  src/accel/metal/numeric/prepare/transform.mm
  src/accel/metal/numeric/run/encode.mm
  src/accel/metal/numeric/run/execute.mm
  src/accel/metal/numeric/run/status.mm
  src/accel/metal/ops.cpp
  src/accel/metal/reduce/execute.mm
  src/accel/metal/reduce/finish.mm
  src/accel/metal/reduce/source.cpp
  src/accel/metal/runtime/execute.mm
  src/accel/metal/runtime/map.mm
  src/accel/metal/runtime/resident/bindings.mm
  src/accel/metal/runtime/resident/windows.mm
  src/accel/metal/runtime/staged.mm
  src/accel/metal/runtime/stats.cpp
  src/accel/metal/scatter/execute.mm
  src/accel/metal/scatter/finish.mm
  src/accel/metal/scatter/source.cpp
  src/accel/metal/scatter/reduce/encode.mm
  src/accel/metal/scatter/reduce/finish.mm
  src/accel/metal/scatter/reduce/pipeline.mm
  src/accel/metal/scatter/reduce/prepare.mm
  src/accel/metal/scatter/reduce/source.cpp
  src/accel/metal/stencil/execute.mm
  src/accel/metal/stencil/finish.mm
  src/accel/metal/stencil/source.cpp
  src/accel/metal/scan/encode/buffers.mm
  src/accel/metal/scan/encode/flags.mm
  src/accel/metal/scan/encode/state.mm
  src/accel/metal/scan/execute.mm
  src/accel/metal/scan/execute/buffers.mm
  src/accel/metal/scan/pipeline.mm
  src/accel/metal/scan/kernel.mm
  src/accel/metal/scan/status.cpp
  src/accel/metal/scan/source.cpp
  src/accel/metal/segmented/encode.mm
  src/accel/metal/segmented/execute.mm
  src/accel/metal/segmented/finish.mm
  src/accel/metal/segmented/pipeline.mm
  src/accel/metal/segmented/source.cpp
  src/accel/metal/segmented/reduce/encode.mm
  src/accel/metal/segmented/reduce/execute.mm
  src/accel/metal/segmented/reduce/finish.mm
  src/accel/metal/segmented/reduce/pipeline.mm
  src/accel/metal/segmented/reduce/prepare.mm
  src/accel/metal/segmented/reduce/source.cpp
  src/accel/metal/sort/execute.mm
  src/accel/metal/sort/finish.mm
  src/accel/metal/sort/shape.cpp
  src/accel/metal/sort/source.cpp
)
