list(APPEND NODE_SOURCES
  src/accel/vulkan/kernel/run.cpp
  src/accel/vulkan/ops.cpp
  src/accel/vulkan/adapter/access.cpp
  src/accel/vulkan/buffer/access.cpp
  src/accel/vulkan/buffer/create.cpp
  src/accel/vulkan/buffer/pool.cpp
  src/accel/vulkan/buffer/resident/batch.cpp
  src/accel/vulkan/buffer/resident/batch/copy.cpp
  src/accel/vulkan/buffer/resident/batch/download.cpp
  src/accel/vulkan/buffer/resident/batch/upload.cpp
  src/accel/vulkan/buffer/resident/create.cpp
  src/accel/vulkan/buffer/resident/download.cpp
  src/accel/vulkan/buffer/resident/lookup.cpp
  src/accel/vulkan/buffer/resident/upload.cpp
  src/accel/vulkan/buffer/stats.cpp
  src/accel/vulkan/command.cpp
  src/accel/vulkan/command/resources.cpp
  src/accel/vulkan/completion.cpp
  src/accel/vulkan/completion/service.cpp
  src/accel/vulkan/collective/pipeline.cpp
  src/accel/vulkan/descriptor.cpp
  src/accel/vulkan/compact/descriptor.cpp
  src/accel/vulkan/compact/execute.cpp
  src/accel/vulkan/compact/finish.cpp
  src/accel/vulkan/compact/pipeline.cpp
  src/accel/vulkan/compact/source.cpp
  src/accel/vulkan/gather/descriptor.cpp
  src/accel/vulkan/gather/execute.cpp
  src/accel/vulkan/gather/finish.cpp
  src/accel/vulkan/gather/pipeline.cpp
  src/accel/vulkan/gather/source.cpp
  src/accel/vulkan/histogram/descriptor.cpp
  src/accel/vulkan/histogram/encode.cpp
  src/accel/vulkan/histogram/execute.cpp
  src/accel/vulkan/histogram/finish.cpp
  src/accel/vulkan/histogram/pipeline.cpp
  src/accel/vulkan/histogram/resources.cpp
  src/accel/vulkan/histogram/source.cpp
  src/accel/vulkan/device.cpp
  src/accel/vulkan/error.cpp
  src/accel/vulkan/extensions.cpp
  src/accel/vulkan/lifecycle.cpp
  src/accel/vulkan/pick/device.cpp
  src/accel/vulkan/pick/instance.cpp
  src/accel/vulkan/pick/reject.cpp
  src/accel/vulkan/pick/result.cpp
  src/accel/vulkan/pick/run.cpp
  src/accel/vulkan/timestamp.cpp
  src/accel/vulkan/cached/pipeline.cpp
  src/accel/vulkan/map/descriptor.cpp
  src/accel/vulkan/map/finish.cpp
  src/accel/vulkan/map/host/buffer.cpp
  src/accel/vulkan/map/resident.cpp
  src/accel/vulkan/numeric/base.cpp
  src/accel/vulkan/numeric/resource.cpp
  src/accel/vulkan/numeric/prepare/factor.cpp
  src/accel/vulkan/numeric/prepare/matrix.cpp
  src/accel/vulkan/numeric/prepare/solve.cpp
  src/accel/vulkan/numeric/prepare/spectrum.cpp
  src/accel/vulkan/numeric/prepare/transform.cpp
  src/accel/vulkan/numeric/run/encode.cpp
  src/accel/vulkan/numeric/run/execute.cpp
  src/accel/vulkan/numeric/run/status.cpp
  src/accel/vulkan/numeric/source/factor.cpp
  src/accel/vulkan/numeric/source/matrix.cpp
  src/accel/vulkan/numeric/source/solve.cpp
  src/accel/vulkan/numeric/source/spectrum.cpp
  src/accel/vulkan/numeric/source/transform.cpp
  src/accel/vulkan/numeric/source/64/factor.cpp
  src/accel/vulkan/numeric/source/64/matrix.cpp
  src/accel/vulkan/numeric/source/64/solve.cpp
  src/accel/vulkan/numeric/source/64/spectrum.cpp
  src/accel/vulkan/numeric/source/64/transform.cpp
  src/accel/vulkan/partition/descriptor.cpp
  src/accel/vulkan/partition/execute.cpp
  src/accel/vulkan/partition/finish.cpp
  src/accel/vulkan/partition/pipeline.cpp
  src/accel/vulkan/partition/source.cpp
  src/accel/vulkan/kernel/context.cpp
  src/accel/vulkan/kernel/control.cpp
  src/accel/vulkan/kernel/command.cpp
  src/accel/vulkan/kernel/batch.cpp
  src/accel/vulkan/kernel/pipeline/evidence.cpp
  src/accel/vulkan/kernel/pipeline/prepare.cpp
  src/accel/vulkan/kernel/pipeline/recurrence.cpp
  src/accel/vulkan/kernel/pipeline/run.cpp
  src/accel/vulkan/kernel/pipeline/source.cpp
  src/accel/vulkan/kernel/pipeline/state.cpp
  src/accel/vulkan/kernel/pipeline/stub.cpp
  src/accel/vulkan/kernel/pipeline/telemetry.cpp
  src/accel/vulkan/kernel/publish.cpp
  src/accel/vulkan/kernel/copy.cpp
  src/accel/vulkan/kernel/window.cpp
  src/accel/vulkan/kernel/prepared.cpp
  src/accel/vulkan/scratch.cpp
  src/accel/vulkan/kernel/finish.cpp
  src/accel/vulkan/kernel/prepare.cpp
  src/accel/vulkan/kernel/view.cpp
  src/accel/vulkan/reduce/descriptor.cpp
  src/accel/vulkan/reduce/execute.cpp
  src/accel/vulkan/reduce/finish.cpp
  src/accel/vulkan/reduce/pipeline.cpp
  src/accel/vulkan/reduce/shape.cpp
  src/accel/vulkan/reduce/source.cpp
  src/accel/vulkan/runtime/buffers.cpp
  src/accel/vulkan/runtime/descriptor.cpp
  src/accel/vulkan/runtime/descriptors.cpp
  src/accel/vulkan/runtime/dispatch.cpp
  src/accel/vulkan/runtime/execute.cpp
  src/accel/vulkan/runtime/host/buffer.cpp
  src/accel/vulkan/runtime/readback.cpp
  src/accel/vulkan/runtime/resident.cpp
  src/accel/vulkan/runtime/window.cpp
  src/accel/vulkan/scatter/descriptor.cpp
  src/accel/vulkan/scatter/execute.cpp
  src/accel/vulkan/scatter/finish.cpp
  src/accel/vulkan/scatter/pipeline.cpp
  src/accel/vulkan/scatter/source.cpp
  src/accel/vulkan/scatter/reduce/encode.cpp
  src/accel/vulkan/scatter/reduce/finish.cpp
  src/accel/vulkan/scatter/reduce/pipeline.cpp
  src/accel/vulkan/scatter/reduce/prepare.cpp
  src/accel/vulkan/scatter/reduce/source.cpp
  src/accel/vulkan/stencil/descriptor.cpp
  src/accel/vulkan/stencil/execute.cpp
  src/accel/vulkan/stencil/finish.cpp
  src/accel/vulkan/stencil/pipeline.cpp
  src/accel/vulkan/stencil/source.cpp
  src/accel/vulkan/scan/descriptor.cpp
  src/accel/vulkan/scan/execute.cpp
  src/accel/vulkan/scan/execute/buffers.cpp
  src/accel/vulkan/scan/pipeline.cpp
  src/accel/vulkan/scan/kernel.cpp
  src/accel/vulkan/scan/source.cpp
  src/accel/vulkan/scan/status.cpp
  src/accel/vulkan/segmented/descriptor.cpp
  src/accel/vulkan/segmented/encode.cpp
  src/accel/vulkan/segmented/execute.cpp
  src/accel/vulkan/segmented/finish.cpp
  src/accel/vulkan/segmented/pipeline.cpp
  src/accel/vulkan/segmented/source.cpp
  src/accel/vulkan/segmented/reduce/encode.cpp
  src/accel/vulkan/segmented/reduce/execute.cpp
  src/accel/vulkan/segmented/reduce/finish.cpp
  src/accel/vulkan/segmented/reduce/pipeline.cpp
  src/accel/vulkan/segmented/reduce/prepare.cpp
  src/accel/vulkan/segmented/reduce/source.cpp
  src/accel/vulkan/sort/execute.cpp
  src/accel/vulkan/sort/finish.cpp
  src/accel/vulkan/sort/pipeline.cpp
  src/accel/vulkan/sort/resources/allocate.cpp
  src/accel/vulkan/sort/resources/bindings.cpp
  src/accel/vulkan/sort/resources/destroy.cpp
  src/accel/vulkan/sort/resources/pass.cpp
  src/accel/vulkan/sort/resources/prepare.cpp
  src/accel/vulkan/sort/resources/shape.cpp
  src/accel/vulkan/sort/shape.cpp
  src/accel/vulkan/sort/source.cpp
  src/accel/vulkan/shader.cpp
  src/accel/vulkan/status.cpp
  src/accel/vulkan/shader/cache.cpp
  src/accel/vulkan/shader/module.cpp
  src/accel/vulkan/shader/tool/compile.cpp
  src/accel/vulkan/shader/tool/hex.cpp
  src/accel/vulkan/shader/tool/process.cpp
  src/accel/vulkan/shader/tool/scratch.cpp
  src/accel/vulkan/shader/tool/spirv.cpp src/accel/vulkan/shader/tool/stem.cpp
)
