set(KERNEL_COMPUTE_CORE_TEST_SOURCES
  tests/contract/run/compute.cpp
  tests/contract/program/compute.cpp
  tests/contract/program/compute/tile.cpp
  tests/contract/program/compute/tile/async.cpp
  tests/contract/program/compute/lowering/cpu.cpp
)

set(KERNEL_COMPUTE_MODEL_TEST_SOURCES
  tests/contract/run/model.cpp
  tests/contract/program/compute/model.cpp
  tests/contract/program/compute/dsl.cpp
  tests/contract/program/compute/dsl/identity.cpp
  tests/contract/program/compute/dsl/cse.cpp
  tests/contract/program/compute/dsl/ops.cpp
  tests/contract/program/compute/dsl/ops/hash.cpp
  tests/contract/program/compute/dsl/ops/noise/value.cpp
  tests/contract/program/compute/dsl/ops/noise/grid.cpp
  tests/contract/program/compute/dsl/ops/norm.cpp
  tests/contract/program/compute/dsl/ops/vec.cpp
  tests/contract/program/compute/dsl/ops/sq.cpp
  tests/contract/program/compute/dsl/ops/metric.cpp
  tests/contract/program/compute/dsl/ops/range.cpp
  tests/contract/program/compute/dsl/ops/aggregate.cpp
  tests/contract/program/compute/dsl/ops/stats.cpp
  tests/contract/program/compute/dsl/ops/moment.cpp
  tests/contract/program/compute/dsl/ops/corr.cpp
  tests/contract/program/compute/dsl/ops/ratio.cpp
  tests/contract/program/compute/dsl/ops/standardize.cpp
  tests/contract/program/compute/dsl/ops/approx.cpp
  tests/contract/program/compute/dsl/ops/transcendental.cpp
  tests/contract/program/compute/dsl/ops/complex.cpp
  tests/contract/program/compute/dsl/ops/window.cpp
  tests/contract/program/compute/dsl/ops/linear.cpp
  tests/contract/program/compute/dsl/ops/matrix.cpp
  tests/contract/program/compute/dsl/ops/affine.cpp
  tests/contract/program/compute/dsl/ops/mix.cpp
  tests/contract/program/compute/dsl/ops/poly.cpp
  tests/contract/program/compute/dsl/ops/interp.cpp
  tests/contract/program/compute/dsl/ops/mask.cpp
  tests/contract/program/compute/dsl/ops/tol.cpp
  tests/contract/program/compute/dsl/ops/piece.cpp
  tests/contract/program/compute/dsl/ops/proj.cpp
  tests/contract/program/compute/dsl/ops/reflect.cpp
  tests/contract/program/compute/dsl/ops/cross.cpp
  tests/contract/program/compute/dsl/ops/line.cpp
  tests/contract/program/compute/dsl/ops/plane.cpp
  tests/contract/program/compute/dsl/ops/fixed/scalar.cpp
  tests/contract/program/compute/dsl/ops/fixed/bit.cpp
  tests/contract/program/compute/dsl/ops/fixed/nonlinear.cpp
  tests/contract/program/compute/dsl/ops/overload.cpp
  tests/contract/program/compute/dsl/reject.cpp
  tests/contract/program/compute/dsl/reject/base.cpp
  tests/contract/program/compute/dsl/reject/binding.cpp
  tests/contract/program/compute/dsl/reject/domain.cpp
  tests/contract/program/compute/dsl/reject/storage.cpp
  tests/contract/program/compute/dsl/escape.cpp
  tests/contract/program/compute/dsl/shape.cpp
  tests/contract/program/compute/dsl/plan.cpp
  tests/contract/program/compute/fusion.cpp
  tests/contract/program/compute/fusion/plan.cpp
  tests/contract/program/compute/fusion/plan/reject.cpp
  tests/contract/program/compute/fusion/plan/success.cpp
  tests/contract/program/compute/fusion/plan/visibility.cpp
  tests/contract/program/compute/fusion/build.cpp
  tests/contract/program/compute/fusion/build/capacity.cpp
  tests/contract/program/compute/fusion/build/carrier.cpp
  tests/contract/program/compute/fusion/build/chain.cpp
  tests/contract/program/compute/fusion/build/output.cpp
  tests/contract/program/compute/fusion/build/pair.cpp
  tests/contract/program/compute/fusion/build/shift.cpp
  tests/contract/program/compute/fusion/nonlinear.cpp
  tests/contract/program/compute/graph.cpp
  tests/contract/program/compute/graph/admission.cpp
  tests/contract/program/compute/graph/identity.cpp
  tests/contract/program/compute/graph/signature/edges.cpp
  tests/contract/program/compute/graph/signature/count.cpp
  tests/contract/program/compute/graph/rejection.cpp
  tests/contract/program/compute/graph/rejection/buffer.cpp
  tests/contract/program/compute/graph/rejection/node.cpp
  tests/contract/program/compute/graph/rejection/numeric.cpp
  tests/contract/program/compute/graph/rejection/primitive.cpp
  tests/contract/program/compute/ir.cpp
  tests/contract/program/compute/backend/lowering.cpp
  tests/contract/program/compute/backend/lowering/base.cpp
  tests/contract/program/compute/backend/lowering/metal.cpp
  tests/contract/program/compute/backend/lowering/names.cpp
  tests/contract/program/compute/backend/lowering/reject.cpp
  tests/contract/program/compute/backend/lowering/reject/model.cpp
  tests/contract/program/compute/backend/lowering/reject/binding.cpp
  tests/contract/program/compute/backend/lowering/reject/carrier.cpp
  tests/contract/program/compute/backend/lowering/reject/domain.cpp
  tests/contract/program/compute/backend/lowering/reject/shape.cpp
  tests/contract/program/compute/backend/lowering/reject/storage.cpp
  tests/contract/program/compute/backend/lowering/artifact.cpp
  tests/contract/program/compute/backend/lowering/runtime.cpp
  tests/contract/program/compute/backend/lowering/emission/reachability.cpp
  tests/contract/program/compute/lowering/vulkan.cpp
  tests/contract/program/compute/lowering/vulkan/base.cpp
  tests/contract/program/compute/lowering/vulkan/expanded.cpp
  tests/contract/program/compute/lowering/vulkan/fixed/64/lane.cpp
  tests/contract/program/compute/lowering/vulkan/scalar.cpp
  tests/contract/program/compute/lowering/vulkan/bit.cpp
  tests/contract/program/compute/lowering/vulkan/nonlinear.cpp
  tests/contract/program/compute/metadata.cpp
  tests/contract/program/compute/numeric/algebra.cpp
  tests/contract/program/compute/numeric/algebra/accuracy.cpp
  tests/contract/program/compute/numeric/algebra/factor.cpp
  tests/contract/program/compute/numeric/algebra/identity.cpp
  tests/contract/program/compute/numeric/algebra/matrix.cpp
  tests/contract/program/compute/numeric/algebra/scratch.cpp
  tests/contract/program/compute/numeric/algebra/solve.cpp
  tests/contract/program/compute/numeric/algebra/spectrum.cpp
  tests/contract/program/compute/plan.cpp
  tests/contract/program/compute/plan/dispatch.cpp
  tests/contract/program/compute/plan/identity.cpp
  tests/contract/program/compute/plan/reject.cpp
  tests/contract/program/compute/plan/shape.cpp
  tests/contract/program/compute/compact.cpp
  tests/contract/program/compute/compact/identity.cpp
  tests/contract/program/compute/compact/reference.cpp
  tests/contract/program/compute/compact/reject.cpp
  tests/contract/program/compute/compact/shape.cpp
  tests/contract/program/compute/gather.cpp
  tests/contract/program/compute/gather/identity.cpp
  tests/contract/program/compute/gather/reference.cpp
  tests/contract/program/compute/gather/reject.cpp
  tests/contract/program/compute/gather/shape.cpp
  tests/contract/program/compute/histogram.cpp tests/contract/program/compute/histogram/identity.cpp
  tests/contract/program/compute/histogram/reference.cpp tests/contract/program/compute/histogram/reject.cpp
  tests/contract/program/compute/histogram/shape.cpp
  tests/contract/program/compute/partition.cpp
  tests/contract/program/compute/partition/identity.cpp
  tests/contract/program/compute/partition/plan.cpp
  tests/contract/program/compute/partition/reference.cpp
  tests/contract/program/compute/reduce.cpp
  tests/contract/program/compute/reduce/identity.cpp
  tests/contract/program/compute/reduce/reference/sum.cpp tests/contract/program/compute/reduce/reference/extrema.cpp
  tests/contract/program/compute/reduce/reference/reject.cpp
  tests/contract/program/compute/reduce/reject.cpp
  tests/contract/program/compute/reduce/shape/plan.cpp tests/contract/program/compute/reduce/shape/ops.cpp
  tests/contract/program/compute/scatter.cpp
  tests/contract/program/compute/scatter/identity.cpp
  tests/contract/program/compute/scatter/reference.cpp
  tests/contract/program/compute/scatter/reject.cpp
  tests/contract/program/compute/scatter/shape.cpp
  tests/contract/program/compute/scatter/reduce.cpp
  tests/contract/program/compute/scan.cpp
  tests/contract/program/compute/scan/identity.cpp
  tests/contract/program/compute/scan/reference.cpp
  tests/contract/program/compute/scan/reject.cpp
  tests/contract/program/compute/scan/shape.cpp
  tests/contract/program/compute/segmented/scan.cpp
  tests/contract/program/compute/segmented/scan/identity.cpp
  tests/contract/program/compute/segmented/scan/reference.cpp
  tests/contract/program/compute/segmented/scan/reject.cpp
  tests/contract/program/compute/segmented/scan/shape.cpp tests/contract/program/compute/segmented/reduce.cpp tests/contract/program/compute/segmented/reduce/identity.cpp tests/contract/program/compute/segmented/reduce/reference.cpp tests/contract/program/compute/segmented/reduce/reject.cpp tests/contract/program/compute/segmented/reduce/shape.cpp
  tests/contract/program/compute/sort.cpp
  tests/contract/program/compute/sort/identity.cpp
  tests/contract/program/compute/sort/reference.cpp
  tests/contract/program/compute/sort/reject.cpp
  tests/contract/program/compute/sort/shape.cpp
  tests/contract/program/compute/stencil.cpp
  tests/contract/program/compute/stencil/identity.cpp
  tests/contract/program/compute/stencil/reference.cpp
  tests/contract/program/compute/stencil/reject.cpp
  tests/contract/program/compute/stencil/shape.cpp
  tests/contract/program/compute/fixed/arithmetic.cpp
  tests/contract/program/compute/fixed/arithmetic/dsl.cpp
  tests/contract/program/compute/fixed/arithmetic/fusion.cpp
  tests/contract/program/compute/fixed/arithmetic/lowering.cpp
  tests/contract/program/compute/fixed/arithmetic/reject.cpp
  tests/contract/program/compute/reject/model.cpp
)
