#pragma once

#include <math64/core/model.hpp>
#include <math64/simd/model.hpp>
#include <math64/simd/mask.hpp>
#include <math64/simd/select.hpp>
#include <math64/simd/memory.hpp>
#include <math64/simd/arithmetic.hpp>
#include <math64/simd/compare.hpp>
#include <math64/simd/reduction.hpp>
#include <math64/fixed/constants.hpp>
#include <math64/fixed/arithmetic.hpp>
#include <math64/fixed/sqrt.hpp>
#include <math64/nonlinear/exp.hpp>
#include <math64/nonlinear/log.hpp>
#include <math64/turn/constants.hpp>
#include <math64/turn/trig.hpp>
#include <math64/turn/atan.hpp>
#include <math64/stat/mean.hpp>
#include <math64/stat/variance.hpp>
#include <math64/stat/rms.hpp>
#include <math64/stat/interpolation.hpp>
#include <math64/geom/vec2x.hpp>
#include <math64/geom/vec3x.hpp>
#include <math64/geom/view.hpp>
#include <math64/geom/vector.hpp>
#include <math64/soa/status.hpp>
#include <math64/soa/validate.hpp>
#include <math64/soa/span.hpp>
#include <math64/soa/geom.hpp>
#include <math64/quant/clamp.hpp>
#include <math64/quant/requant.hpp>
#include <math64/nn/model.hpp>
#include <math64/nn/dot.hpp>
#include <math64/nn/activation.hpp>
#include <math64/nn/norm.hpp>
#include <math64/nn/rope.hpp>
#include <math64/prob/model.hpp>
#include <math64/prob/max.hpp>
#include <math64/prob/logsumexp.hpp>
#include <math64/prob/softmax.hpp>
#include <math64/prob/logsoftmax.hpp>
#include <math64/prob/softplus.hpp>
#include <math64/prob/logsigmoid.hpp>
#include <math64/prob/entropy/cross.hpp>
#include <math64/rl/recurrence.hpp>
