#!/usr/bin/env python3
"""Check Node-private native headers for standalone compilation and ODR safety."""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
import sys
import tempfile
from typing import Sequence

# This contract is a source-tree tool; generated bytecode does not belong
# beside its checked-in modules.  Probe artifacts are likewise kept in the
# configured build scratch directory below.
sys.dont_write_bytecode = True

try:
    from .availability import run_availability_probe
    from .fixtures import FixtureError, run_self_tests
    from .model import (
        CompileContext,
        ModelError,
        all_scoped_headers,
        flags_for_mode,
        load_compile_database,
        sdk_available,
        select_context,
    )
    from .probe import (
        ProbeError,
        ProcessResult,
        compile_stdin,
        header_source,
        run_odr_probe,
        short_output,
    )
except ImportError:  # Direct invocation from CTest/source tree.
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from availability import run_availability_probe  # type: ignore[no-redef]
    from fixtures import FixtureError, run_self_tests  # type: ignore[no-redef]
    from model import (  # type: ignore[no-redef]
        CompileContext,
        ModelError,
        all_scoped_headers,
        flags_for_mode,
        load_compile_database,
        sdk_available,
        select_context,
    )
    from probe import (  # type: ignore[no-redef]
        ProbeError,
        ProcessResult,
        compile_stdin,
        header_source,
        run_odr_probe,
        short_output,
    )


class ContractError(RuntimeError):
    """A failed native-header contract or missing configured input."""


def _under(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
    except ValueError:
        return False
    return True


def _probe_headers(
    context: CompileContext,
    headers: Sequence[Path],
    flags: Sequence[str],
    label: str,
    jobs: int,
) -> None:
    def probe(header: Path) -> tuple[Path, ProcessResult]:
        return header, compile_stdin(context, flags, header_source(header))

    failures: list[tuple[Path, ProcessResult]] = []
    with ThreadPoolExecutor(max_workers=max(1, min(jobs, 4, len(headers)))) as executor:
        pending = [executor.submit(probe, header) for header in headers]
        for future in as_completed(pending):
            header, result = future.result()
            if result.returncode != 0:
                failures.append((header, result))
    if failures:
        failures.sort(key=lambda item: str(item[0]))
        details = "\n".join(
            f"  {header}: {short_output(result.output)}" for header, result in failures
        )
        raise ContractError(f"{label} standalone header probe failed ({len(failures)}):\n{details}")


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", required=True, type=Path, help="repository source root")
    parser.add_argument("--build", required=True, type=Path, help="configured CMake build directory")
    parser.add_argument("--jobs", type=int, default=4, help="parallel header probes (capped at four)")
    return parser


def _run_contract(arguments: argparse.Namespace) -> int:
    root = arguments.root.resolve()
    build = arguments.build.resolve()
    if not root.is_dir():
        raise ContractError(f"repository root is not a directory: {root}")
    if not build.is_dir():
        raise ContractError(f"configured build directory is not a directory: {build}")
    database = build / "compile_commands.json"
    if not database.is_file():
        raise ContractError(f"configured compile database is missing: {database}")
    if arguments.jobs < 1:
        raise ContractError("--jobs must be positive")

    try:
        rows = load_compile_database(database, root)
        headers = all_scoped_headers(root)
    except ModelError as error:
        raise ContractError(str(error)) from error
    vulkan = select_context(rows, root, "vulkan")
    metal = select_context(rows, root, "metal")
    portable = select_context(rows, root, "portable") or vulkan
    if vulkan is None:
        raise ContractError("compile database has no native Vulkan C++ anchor row")
    if portable is None:
        raise ContractError("compile database has no portable C++ anchor row")
    if metal is None:
        # Metal-disabled/non-Apple graphs may not have a Metal-specific C++
        # row. Use the portable context, but make that fallback observable.
        metal = portable
        metal_fallback = True
    else:
        metal_fallback = False

    vulkan_sdk = sdk_available(vulkan, "vulkan")
    metal_sdk = sdk_available(metal, "metal")
    native_headers = tuple(
        header for header in headers if _under(header, root / "node" / "src" / "accel" / "vulkan")
    )
    metal_headers = tuple(
        header for header in headers if _under(header, root / "node" / "src" / "accel" / "metal")
    )
    print(f"scope_count={len(headers)}")
    print(f"vulkan_anchor={vulkan.source}")
    print(f"metal_anchor={metal.source}")
    print(f"metal_anchor_fallback={'yes' if metal_fallback else 'no'}")
    print(f"portable_anchor={portable.source}")
    print(f"sdk.vulkan={'on' if vulkan_sdk else 'unavailable'}")
    print(f"sdk.metal={'on' if metal_sdk else 'unavailable'}")

    with tempfile.TemporaryDirectory(prefix="native-header-contract-", dir=str(build)) as scratch_name:
        scratch = Path(scratch_name)
        try:
            run_self_tests(portable, scratch / "self-tests")
        except FixtureError as error:
            raise ContractError(str(error)) from error
        print("self_tests=missing_include,sdk_only,duplicate_definition")

        off_flags = flags_for_mode(portable, "off")
        _probe_headers(portable, headers, off_flags, "SDK-off", arguments.jobs)
        print(f"off_count={len(headers)}")

        on_count = 0
        if vulkan_sdk:
            on_flags = flags_for_mode(vulkan, "on")
            _probe_headers(vulkan, native_headers, on_flags, "Vulkan SDK-on", arguments.jobs)
            try:
                run_odr_probe(vulkan, on_flags, headers, scratch / "odr-vulkan-on", "Vulkan SDK-on")
            except ProbeError as error:
                raise ContractError(str(error)) from error
            on_count += len(native_headers)
            print(f"on.vulkan_count={len(native_headers)}")
            print("on.vulkan_status=passed")
        else:
            print("on.vulkan_count=0")
            print("on.vulkan_status=skipped: Vulkan SDK unavailable in configured context")

        if metal_sdk:
            on_flags = flags_for_mode(metal, "on")
            _probe_headers(metal, metal_headers, on_flags, "Metal SDK-on", arguments.jobs)
            try:
                run_odr_probe(metal, on_flags, headers, scratch / "odr-metal-on", "Metal SDK-on")
            except ProbeError as error:
                raise ContractError(str(error)) from error
            on_count += len(metal_headers)
            print(f"on.metal_count={len(metal_headers)}")
            print("on.metal_status=passed")
        else:
            print("on.metal_count=0")
            print("on.metal_status=skipped: Metal SDK unavailable in configured context")

        try:
            run_odr_probe(portable, off_flags, headers, scratch / "odr-sdk-off", "SDK-off")
        except ProbeError as error:
            raise ContractError(str(error)) from error
        print("odr.sdk_off=passed")
        try:
            run_availability_probe(portable, rows, root, scratch / "availability-sdk-off")
        except ProbeError as error:
            raise ContractError(str(error)) from error
        print("availability.sdk_off=linked_and_executed")
        print(f"on_count={on_count}")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    try:
        return _run_contract(_parser().parse_args(argv))
    except ContractError as error:
        print(f"native-header-contract: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
