set(KERNEL_REDUCTION_SOURCES
  src/reduction/fold/graph.cpp
  src/reduction/fold/graph/validate.cpp
  src/reduction/fold/graph/validation/edges.cpp
  src/reduction/fold/graph/validation/failure.cpp
  src/reduction/fold/graph/validation/nodes.cpp
  src/reduction/fold/graph/validation/shape.cpp
  src/reduction/fold/graph/validation/slots.cpp
  src/reduction/fold/ordered.cpp
  src/reduction/fold/reduce.cpp
  src/reduction/fold/scratch.cpp
  src/reduction/fold/spec/combine.cpp
  src/reduction/fold/spec/describe.cpp
  src/reduction/fold/spec/identity.cpp
  src/reduction/fold/spec/laws.cpp
  src/reduction/fold/spec/policy.cpp
  src/reduction/graph/build.cpp
  src/reduction/graph/build/populate.cpp
  src/reduction/graph/build/populate/slots.cpp
  src/reduction/graph/build/populate/tree.cpp
  src/reduction/graph/build/result.cpp
  src/reduction/graph/state.cpp
  src/reduction/graph/validate.cpp
  src/reduction/graph/validate/edges.cpp
  src/reduction/graph/validate/nodes.cpp
  src/reduction/graph/validate/result.cpp
  src/reduction/graph/validate/shape.cpp
  src/reduction/graph/view.cpp
  src/reduction/slots.cpp
  src/reduction/strict/add.cpp
  src/reduction/strict/add/compose.cpp
  src/reduction/strict/add/mantissa.cpp
  src/reduction/strict/add/special.cpp
  src/reduction/strict/decode.cpp
  src/reduction/strict/format.cpp
  src/reduction/strict/policy.cpp
  src/reduction/strict/round.cpp
)
