set(KERNEL_SCHEDULE_SOURCES
  src/schedule/planner/balanced.cpp
  src/schedule/planner/capacity.cpp
  src/schedule/planner/capacity/minimax.cpp
  src/schedule/planner/capacity/work.cpp
  src/schedule/planner/compile.cpp
  src/schedule/planner/failure.cpp
  src/schedule/planner/math.cpp
  src/schedule/planner/partition.cpp
  src/schedule/planner/projection/convert.cpp
  src/schedule/planner/projection/project.cpp
  src/schedule/planner/uniform/dynamic.cpp
  src/schedule/planner/uniform/unit.cpp
  src/schedule/planner/view.cpp
  src/schedule/workspace/capacity/proof.cpp
  src/schedule/workspace/capacity/reservation.cpp
  src/schedule/workspace/capacity/runtime.cpp
  src/schedule/workspace/capacity/set.cpp
  src/schedule/workspace/compile.cpp
  src/schedule/workspace/compile/failure.cpp
  src/schedule/workspace/compile/standard.cpp
  src/schedule/workspace/compile/weighted.cpp
  src/schedule/workspace/packet.cpp
  src/schedule/workspace/reservation/margin.cpp
  src/schedule/workspace/reservation/normalize.cpp
  src/schedule/workspace/reservation/satisfied.cpp
  src/schedule/workspace/placement/affinity.cpp
  src/schedule/workspace/placement/crossings.cpp
  src/schedule/workspace/placement/metadata.cpp
  src/schedule/workspace/placement/schema.cpp
  src/schedule/workspace/placement/telemetry.cpp
  src/schedule/workspace/state.cpp
  src/schedule/workspace/telemetry/compile.cpp
  src/schedule/workspace/telemetry/record.cpp
  src/schedule/workspace/weighted.cpp
  src/schedule/workspace/weighted/assign/eight.cpp
  src/schedule/workspace/weighted/assign/heap.cpp
  src/schedule/workspace/weighted/assign.cpp
  src/schedule/workspace/weighted/buffers.cpp
  src/schedule/workspace/weighted/capacity.cpp
  src/schedule/workspace/weighted/order.cpp
  src/schedule/workspace/weighted/partitions.cpp
  src/schedule/workspace/weighted/scatter.cpp
  src/schedule/workspace/weighted/source.cpp
  src/schedule/workspace/weighted/state.cpp
)
