include_guard(GLOBAL)

include("${CMAKE_CURRENT_LIST_DIR}/labels.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/routes.cmake")

function(rund_node_target_case_file out target)
  list(LENGTH NODE_TEST_CASES case_count)
  list(LENGTH NODE_TEST_CASE_SYMBOLS symbol_count)
  list(LENGTH NODE_TEST_CASE_GROUPS group_count)
  if(NOT case_count EQUAL symbol_count OR NOT case_count EQUAL group_count)
    message(FATAL_ERROR "Node test registry fields disagree")
  endif()

  set(content)
  set(target_case_count 0)
  if(case_count GREATER 0)
    math(EXPR last_case "${case_count} - 1")
    foreach(case_index RANGE 0 ${last_case})
      list(GET NODE_TEST_CASES ${case_index} name)
      list(GET NODE_TEST_CASE_SYMBOLS ${case_index} symbol)
      list(GET NODE_TEST_CASE_GROUPS ${case_index} group)
      rund_node_route(route_target unused_resource "${group}")
      if(route_target STREQUAL target)
        string(APPEND content
          "RUND_NODE_TEST_CASE(\"${name}\", ${symbol})\n")
        math(EXPR target_case_count "${target_case_count} + 1")
      endif()
    endforeach()
  endif()
  if(target_case_count EQUAL 0)
    message(FATAL_ERROR "Node test target ${target} has no routed cases")
  endif()

  set(dispatch_dir "${CMAKE_CURRENT_BINARY_DIR}/node-contract/dispatch")
  file(MAKE_DIRECTORY "${dispatch_dir}")
  set(dispatch_file "${dispatch_dir}/${target}.def")
  file(GENERATE OUTPUT "${dispatch_file}" CONTENT "${content}")
  set(${out} "${dispatch_file}" PARENT_SCOPE)
endfunction()

function(rund_node_target_link_profiles out target)
  list(LENGTH NODE_TEST_CASES case_count)
  list(LENGTH NODE_TEST_CASE_GROUPS group_count)
  list(LENGTH NODE_TEST_CASE_LINK_PROFILES profile_count)
  if(NOT case_count EQUAL group_count OR
     NOT case_count EQUAL profile_count)
    message(FATAL_ERROR
      "Node test registry cannot derive target link closure")
  endif()

  set(profiles)
  if(case_count GREATER 0)
    math(EXPR last_case "${case_count} - 1")
    foreach(case_index RANGE 0 ${last_case})
      list(GET NODE_TEST_CASE_GROUPS ${case_index} group)
      rund_node_route(route_target unused_resource "${group}")
      if(route_target STREQUAL target)
        list(GET NODE_TEST_CASE_LINK_PROFILES ${case_index} profile)
        list(APPEND profiles "${profile}")
      endif()
    endforeach()
  endif()
  if(NOT profiles)
    message(FATAL_ERROR
      "Node test target ${target} has no registry link profiles")
  endif()
  list(REMOVE_DUPLICATES profiles)
  set(${out} ${profiles} PARENT_SCOPE)
endfunction()

function(rund_node_group out_rows group target resource)
  cmake_parse_arguments(RUND_GROUP "" "" "CASES" ${ARGN})
  if(NOT RUND_GROUP_CASES)
    message(FATAL_ERROR "Node test group ${group} has no cases")
  endif()

  rund_node_labels(labels "${group}")
  set(test "node.${group}")
  if(group MATCHES "^accel\\.")
    set(test "${group}")
  endif()
  set(backend_args)
  if(NOT RUND_NODE_FOCUSED_BACKEND STREQUAL "")
    list(APPEND backend_args --backend "${RUND_NODE_FOCUSED_BACKEND}")
  endif()
  set(effective_resource "${resource}")
  if(RUND_NODE_FOCUSED_CASE)
    rund_node_case_route(
      effective_target effective_resource unused_profile
      "${RUND_NODE_FOCUSED_CASE}" "${RUND_NODE_FOCUSED_BACKEND}")
    if(NOT effective_target STREQUAL target)
      message(FATAL_ERROR
        "Focused Node case ${RUND_NODE_FOCUSED_CASE} changed target")
    endif()
  endif()
  set(resource_args)
  if(NOT effective_resource STREQUAL "-")
    list(APPEND resource_args RESOURCE_LOCK "${effective_resource}")
  endif()
  rund_node_case(${test}
    BUILD_TARGETS ${target}
    COMMAND
      $<TARGET_FILE:${target}>
      ${backend_args}
      --case
      ${RUND_GROUP_CASES}
    LABELS rund_node rund_contract rund_owner_local ${labels}
    ${resource_args})

  set(rows)
  foreach(name IN LISTS RUND_GROUP_CASES)
    rund_node_case_route(
      case_target case_resource profile "${name}"
      "${RUND_NODE_FOCUSED_BACKEND}")
    if(NOT case_target STREQUAL target)
      message(FATAL_ERROR "Node case ${name} changed its routed target")
    endif()
    list(APPEND rows
      "${name}\t${target}\t${case_resource}\t${profile}")
  endforeach()
  set(${out_rows} ${rows} PARENT_SCOPE)
endfunction()

function(rund_node_tag_cohorts out tag)
  string(SHA256 tag_key "${tag}")
  get_property(cohorts_set GLOBAL PROPERTY
    "RUND_NODE_TAG_COHORTS_${tag_key}" SET)
  if(cohorts_set)
    get_property(cohorts GLOBAL PROPERTY
      "RUND_NODE_TAG_COHORTS_${tag_key}")
    set(${out} ${cohorts} PARENT_SCOPE)
    return()
  endif()

  rund_node_cases_with_tag(tagged_cases "${tag}")
  if(NOT tagged_cases)
    message(FATAL_ERROR "Node test tag has no cases: ${tag}")
  endif()

  set(keys)
  foreach(name IN LISTS tagged_cases)
    list(FIND NODE_TEST_CASES "${name}" case_index)
    list(GET NODE_TEST_CASE_GROUPS ${case_index} group)
    list(GET NODE_TEST_CASE_LINK_PROFILES ${case_index} profile)
    rund_node_route(unused_target resource "${group}")
    string(SHA256 key "${profile}|${resource}")
    set(case_var "tagged_cases_${key}")
    list(APPEND ${case_var} "${name}")
    set(row "${key}|${profile}|${resource}")
    list(FIND keys "${row}" known_key)
    if(known_key EQUAL -1)
      list(APPEND keys "${row}")
    endif()
  endforeach()

  set(cohorts)
  foreach(row IN LISTS keys)
    string(REPLACE "|" ";" fields "${row}")
    list(GET fields 0 key)
    list(GET fields 1 profile)
    list(GET fields 2 resource)
    set(case_var "tagged_cases_${key}")
    string(REPLACE ";" "," encoded_cases "${${case_var}}")
    list(APPEND cohorts "${profile}|${resource}|${encoded_cases}")
  endforeach()
  set_property(GLOBAL PROPERTY
    "RUND_NODE_TAG_COHORTS_${tag_key}" "${cohorts}")
  set(${out} ${cohorts} PARENT_SCOPE)
endfunction()

function(rund_node_tagged_groups tag)
  rund_node_tag_cohorts(cohorts "${tag}")

  # Colons belong to the public tag namespace. CMake and Ninja reserve them in
  # generated identifiers, so the build graph uses the same segments joined by
  # dots without changing the registry identity.
  string(REPLACE ":" "." tag_key "${tag}")
  set(test_names)
  foreach(cohort IN LISTS cohorts)
    string(REPLACE "|" ";" fields "${cohort}")
    list(GET fields 0 profile)
    list(GET fields 1 resource)
    list(GET fields 2 encoded_cases)
    string(REPLACE "," ";" tagged_cases "${encoded_cases}")
    set(target "node-${tag_key}-${profile}")
    set(test "node.${tag_key}.${profile}")
    list(FIND test_names "${test}" duplicate_test)
    if(NOT duplicate_test EQUAL -1)
      message(FATAL_ERROR
        "Node tag ${tag} needs two resources for link profile ${profile}")
    endif()
    list(APPEND test_names "${test}")

    rund_node_subset_test_target(${target} CASES ${tagged_cases})
    set(resource_args)
    if(NOT resource STREQUAL "-")
      list(APPEND resource_args RESOURCE_LOCK "${resource}")
    endif()
    rund_node_case(${test}
      BUILD_TARGETS ${target}
      COMMAND
        $<TARGET_FILE:${target}>
        --case
        ${tagged_cases}
      LABELS rund_node rund_contract rund_owner_local "rund_${tag_key}"
      ${resource_args})
  endforeach()
endfunction()

function(rund_node_groups)
  list(LENGTH NODE_TEST_CASES case_count)
  list(LENGTH NODE_TEST_CASE_GROUPS case_group_count)
  if(NOT case_count EQUAL case_group_count)
    message(FATAL_ERROR "Node test case and group counts disagree")
  endif()

  if(case_count GREATER 0)
    math(EXPR last_case "${case_count} - 1")
    foreach(case_index RANGE 0 ${last_case})
      list(GET NODE_TEST_CASES ${case_index} name)
      list(GET NODE_TEST_CASE_GROUPS ${case_index} group)
      rund_node_route_index(route_index "${group}")
      if(RUND_NODE_FOCUSED_CASE)
        list(FIND RUND_NODE_FOCUSED_CASES "${name}" focus_index)
        if(focus_index EQUAL -1)
          continue()
        endif()
      endif()
      set(var "route_cases_${route_index}")
      list(APPEND ${var} "${name}")
    endforeach()
  endif()

  set(index_rows)
  set(registered_index_cases)
  list(LENGTH RUND_NODE_ROUTE_GROUPS route_count)
  math(EXPR last_route "${route_count} - 1")
  foreach(route_index RANGE 0 ${last_route})
    list(GET RUND_NODE_ROUTE_GROUPS ${route_index} group)
    list(GET RUND_NODE_ROUTE_TARGETS ${route_index} target)
    list(GET RUND_NODE_ROUTE_RESOURCES ${route_index} resource)
    set(var "route_cases_${route_index}")
    set(enabled OFF)
    if(group MATCHES "^accel\\." AND RUND_TEST_ACCEL)
      set(enabled ON)
    elseif(NOT group MATCHES "^accel\\." AND RUND_TEST_NODE)
      set(enabled ON)
    endif()
    if(DEFINED ${var} AND NOT "${${var}}" STREQUAL "" AND enabled)
      if(NOT TARGET ${target})
        message(FATAL_ERROR "Missing Node test target ${target}")
      endif()
      list(APPEND registered_index_cases ${${var}})
      rund_node_group(group_rows "${group}" "${target}" "${resource}"
        CASES ${${var}})
      list(APPEND index_rows ${group_rows})
    endif()
  endforeach()

  set(index_cases)
  foreach(row IN LISTS index_rows)
    string(REPLACE "\t" ";" fields "${row}")
    list(LENGTH fields field_count)
    if(NOT field_count EQUAL 4)
      message(FATAL_ERROR "Malformed Node test index row: ${row}")
    endif()
    list(GET fields 0 name)
    list(APPEND index_cases "${name}")
  endforeach()
  list(LENGTH index_rows index_count)
  set(unique_index_cases ${index_cases})
  list(REMOVE_DUPLICATES unique_index_cases)
  list(LENGTH unique_index_cases unique_index_count)
  if(NOT unique_index_count EQUAL index_count)
    message(FATAL_ERROR "Duplicate Node test index case")
  endif()
  list(SORT index_cases)
  list(SORT registered_index_cases)
  if(NOT "${index_cases}" STREQUAL "${registered_index_cases}")
    message(FATAL_ERROR
      "Node test index does not cover every enabled registered case once")
  endif()
  list(SORT index_rows)
  list(JOIN index_rows "\n" index_content)
  if(index_count GREATER 0)
    string(APPEND index_content "\n")
  endif()

  get_property(index_registered GLOBAL PROPERTY RUND_NODE_INDEX_REGISTERED)
  if(index_registered)
    message(FATAL_ERROR "Node test index generation registered more than once")
  endif()
  set_property(GLOBAL PROPERTY RUND_NODE_INDEX_REGISTERED TRUE)
  set(index_dir "${CMAKE_CURRENT_BINARY_DIR}/node-contract")
  file(MAKE_DIRECTORY "${index_dir}")
  file(GENERATE OUTPUT "${index_dir}/index.tsv" CONTENT "${index_content}")
endfunction()
