list(APPEND NODE_SOURCES
  src/compute/status.cpp
  src/compute/compile/service.cpp
  src/compute/open/cpu.cpp
  src/compute/device/info.cpp
  src/compute/buffer.cpp
  src/compute/buffer/write.cpp
  src/compute/expression/arity.cpp
  src/compute/expression/build.cpp
  src/compute/map/compile/check.cpp
  src/compute/map/compile/cpu.cpp
  src/compute/map/compile/emit.cpp
  src/compute/map/compile/model.cpp
  src/compute/map/compile/operation.cpp
  src/compute/map/compile/replay.cpp
  src/compute/cpu/arena.cpp
  src/compute/cpu/prepared.cpp
  src/compute/cpu/run/execute.cpp
  src/compute/cpu/run/primitive.cpp
  src/compute/cpu/run/primitive/algebra.cpp
  src/compute/run/value.cpp
  src/compute/job/control/bind.cpp
  src/compute/job/control/cache.cpp
  src/compute/job/control/prepare.cpp
  src/compute/job/control/read.cpp
  src/compute/job/control/run.cpp
  src/compute/job/control/stats.cpp
  src/compute/job/control/validate.cpp
  src/compute/job/control/view.cpp
  src/compute/job/cpu/advance.cpp
  src/compute/job/cpu/run.cpp
  src/compute/job/cpu/step.cpp
  src/compute/job/cpu/submit.cpp
  src/compute/job/cpu/tile.cpp
  src/compute/job/write.cpp
  src/compute/cpu/map.cpp
  src/compute/cpu/view.cpp
  src/compute/cpu/run/state.cpp
  src/compute/cpu/scratch.cpp
  src/compute/run/read.cpp
  src/compute/stats.cpp
  src/compute/telemetry.cpp
  src/compute/program/cache.cpp
  src/compute/program/introspection.cpp
  src/compute/pipeline/build.cpp
  src/compute/pipeline/async.cpp
  src/compute/pipeline/claim.cpp
  src/compute/pipeline/plan.cpp
  src/compute/pipeline/plan/admit.cpp
  src/compute/pipeline/plan/arena.cpp
  src/compute/pipeline/plan/backend.cpp
  src/compute/pipeline/plan/bind.cpp
  src/compute/pipeline/plan/contract.cpp
  src/compute/pipeline/plan/memory.cpp
  src/compute/pipeline/plan/memory/accel.cpp
  src/compute/pipeline/plan/memory/commitment.cpp
  src/compute/pipeline/plan/memory/cpu.cpp
  src/compute/pipeline/plan/memory/host.cpp
  src/compute/pipeline/plan/memory/materialize.cpp
  src/compute/pipeline/plan/memory/model.cpp
  src/compute/pipeline/plan/memory/summary.cpp
  src/compute/pipeline/plan/memory/workload.cpp
  src/compute/pipeline/plan/memory/workspace.cpp
  src/compute/pipeline/output.cpp
  src/compute/pipeline/plan/publication.cpp
  src/compute/pipeline/plan/resource.cpp
  src/compute/pipeline/plan/schedule.cpp
  src/compute/pipeline/plan/scratch.cpp
  src/compute/pipeline/residency/identity.cpp
  src/compute/pipeline/residency/authority.cpp
  src/compute/pipeline/residency/integration.cpp
  src/compute/pipeline/residency/model.cpp
  src/compute/pipeline/residency/planner.cpp
  src/compute/pipeline/read.cpp
  src/compute/pipeline/transfer/batch/model.cpp
  src/compute/pipeline/transfer/batch/publication.cpp
  src/compute/pipeline/transfer/batch/upload.cpp
  src/compute/pipeline/transfer/batch/download.cpp
  src/compute/pipeline/write.cpp
  src/compute/pipeline/snapshot.cpp
  src/compute/pipeline/profile.cpp
  src/compute/pipeline/run.cpp
  src/compute/pipeline/run/cpu.cpp
  src/compute/pipeline/run/finish.cpp
  src/compute/pipeline/run/memory.cpp
  src/compute/pipeline/run/profile.cpp
  src/compute/pipeline/run/publish.cpp
  src/compute/pipeline/run/start.cpp
  src/compute/resource/plan.cpp
  src/compute/resource/memory.cpp
  src/compute/resource/memory/arena.cpp
  src/compute/memory/arena.cpp
  src/compute/memory/device.cpp
  src/compute/memory/program.cpp
  src/compute/memory/job.cpp
  src/compute/job/profile.cpp
  src/compute/graph/build/create.cpp
  src/compute/graph/build/map.cpp
  src/compute/graph/build/output.cpp
  src/compute/graph/build/primitive/build.cpp
  src/compute/graph/build/primitive/node.cpp
  src/compute/graph/build/primitive/option.cpp
  src/compute/graph/build/scan.cpp
  src/compute/graph/describe/build.cpp
  src/compute/graph/describe/finish.cpp
  src/compute/graph/describe/hazard.cpp
  src/compute/graph/describe/node.cpp
  src/compute/graph/describe/resource.cpp
  src/compute/graph/compile/entry.cpp
  src/compute/graph/compile/finish.cpp
  src/compute/graph/compile/lower.cpp
  src/compute/graph/compile/map.cpp
  src/compute/graph/compile/primitive.cpp
  src/compute/graph/compile/program.cpp
  src/compute/graph/compile/scan.cpp
  src/compute/flow/compile.cpp
  src/compute/flow/convert.cpp
  src/compute/flow/create.cpp
  src/compute/flow/matrix.cpp
  src/compute/flow/plan/expression.cpp
  src/compute/flow/plan/fuse.cpp
  src/compute/flow/plan/graph.cpp
  src/compute/flow/plan/live.cpp
  src/compute/flow/plan/order.cpp
  src/compute/flow/query.cpp
  src/compute/flow/stage/binary.cpp
  src/compute/flow/stage/input.cpp
  src/compute/flow/stage/scan.cpp
  src/compute/flow/stage/select.cpp
  src/compute/flow/stage/unary.cpp
  src/compute/virtual/backing.cpp
  src/compute/virtual/active.cpp
  src/compute/virtual/buffer.cpp
  src/compute/virtual/observe.cpp
  src/compute/virtual/prepare.cpp
  src/compute/virtual/run.cpp
  src/compute/virtual/run/backing.cpp
  src/compute/virtual/run/evidence.cpp
  src/compute/virtual/run/projection.cpp
  src/compute/virtual/run/sample.cpp
  src/compute/virtual/run/wave.cpp
  src/compute/virtual/stats.cpp
)

if(RUND_TEST_NODE)
  set_source_files_properties(src/compute/open/cpu.cpp PROPERTIES
    COMPILE_DEFINITIONS RUND_NODE_OPEN_PROBE=1)
endif()
