list(APPEND NODE_SOURCES
  src/host/chrono.cpp
  src/host/env.cpp
  src/host/event.cpp
  src/host/replay/layout.cpp
  src/host/io.cpp
  src/host/net/address.cpp
  src/host/net/bytes.cpp
  src/host/net/cancel.cpp
  src/host/net/connection.cpp
  src/host/net/datagram.cpp
  src/host/net/drain.cpp
  src/host/net/event/record.cpp
  src/host/net/frame/io.cpp
  src/host/net/handoff.cpp
  src/host/net/interest.cpp
  src/host/net/lifecycle.cpp
  src/host/net/limits.cpp
  src/host/net/listener.cpp
  src/host/net/native/result.cpp
  src/host/net/options.cpp
  src/host/net/payload/hash.cpp
  src/host/net/ready/many.cpp
  src/host/net/ready/set.cpp
  src/host/net/ready.cpp
  src/host/net/registry/admission.cpp
  src/host/net/registry/lifecycle.cpp
  src/host/net/registry/state.cpp
  src/host/net/registry/validation.cpp
  src/host/net/socket.cpp
  src/host/net/scheduler.cpp
  src/host/net/vectored.cpp
  src/host/random.cpp
  src/host/hash/bytes.cpp
)
