  struct Control {
    std::mutex mutex{};
    std::uint64_t owner_scheduler_id = 0u;
    std::uint64_t channel_id = 0u;
    std::size_t capacity = 0u;
    std::size_t task_capacity = 0u;
    std::vector<std::optional<T>> buffer{};
    std::size_t buffer_head = 0u;
    std::size_t buffer_size = 0u;
    std::vector<std::uint8_t> send_waiting{};
    std::vector<std::uint8_t> recv_waiting{};
    std::vector<std::uint64_t> next_send_waiter{};
    std::vector<std::uint64_t> next_recv_waiter{};
    std::vector<std::optional<T>> send_value_by_task{};
    std::vector<std::optional<Rendezvous>> rendezvous_by_receiver{};
    std::vector<std::optional<CompletedSend>> completed_send_by_task{};
    std::vector<std::uint32_t> counted_wake_count{};
    std::uint64_t match_sequence = 0u;
    std::uint64_t baton_epoch = 0u;
    std::uint64_t send_waiter_head = 0u;
    std::uint64_t send_waiter_tail = 0u;
    std::uint64_t recv_waiter_head = 0u;
    std::uint64_t recv_waiter_tail = 0u;
    std::size_t send_waiter_count = 0u;
    std::size_t recv_waiter_count = 0u;
    std::size_t rendezvous_count = 0u;
    std::size_t completed_send_count = 0u;
    std::size_t counted_wake_entries = 0u;
    std::size_t in_flight_wakes = 0u;
    bool closed = false;
    bool scheduler_released = false;
  };
