#!/usr/bin/env perl
use strict;
use warnings;

use Cwd qw(abs_path);
use File::Spec;

@ARGV == 1 or die "usage: tools/internal/toolchain/compiler <build>\n";
my $build = abs_path($ARGV[0]) // die "missing configured build $ARGV[0]\n";
my $cache = "$build/CMakeCache.txt";
open my $input, '<', $cache or die "cannot read $cache: $!\n";
my @compiler;
while (my $line = <$input>) {
  chomp $line;
  push @compiler, $1
      if $line =~ /\ACMAKE_CXX_COMPILER:FILEPATH=(.*)\z/;
}
close $input or die "cannot close $cache: $!\n";
@compiler == 1 && $compiler[0] ne '' && $compiler[0] !~ /[\t\r\n]/
    or die "configured build has no unique C++ compiler\n";
File::Spec->file_name_is_absolute($compiler[0])
    or die "configured compiler path is not absolute: $compiler[0]\n";
my $path = $compiler[0];
-f $path && -x $path
    or die "configured compiler is not executable: $path\n";
print "$path\n";
