cmake_minimum_required(VERSION 3.20)

set(route_file "$ENV{RUND_CTEST_ROUTES}")
set(pattern "$ENV{RUND_CTEST_PATTERN}")
if(route_file STREQUAL "")
  message(FATAL_ERROR "RUND_CTEST_ROUTES is required")
endif()
if(pattern STREQUAL "")
  message(FATAL_ERROR "RUND_CTEST_PATTERN is required")
endif()
get_filename_component(route_file "${route_file}" ABSOLUTE)
if(NOT EXISTS "${route_file}")
  message(FATAL_ERROR "CTest route index is missing: ${route_file}")
endif()

file(STRINGS "${route_file}" rows)
list(LENGTH rows row_count)
if(row_count LESS 3)
  message(FATAL_ERROR "CTest route index is incomplete")
endif()
list(GET rows 0 header)
if(NOT header STREQUAL "routes")
  message(FATAL_ERROR "CTest route index has no canonical header")
endif()
math(EXPR seal_index "${row_count} - 1")
list(GET rows ${seal_index} seal_row)
string(REPLACE "\t" ";" seal_fields "${seal_row}")
list(LENGTH seal_fields seal_field_count)
if(NOT seal_field_count EQUAL 2)
  message(FATAL_ERROR "CTest route index has a malformed seal")
endif()
list(GET seal_fields 0 seal_kind)
list(GET seal_fields 1 expected_seal)
if(NOT seal_kind STREQUAL "seal" OR
   NOT expected_seal MATCHES "^[0-9a-f][0-9a-f]+$" OR
   NOT expected_seal MATCHES "^................................................................$")
  message(FATAL_ERROR "CTest route index has a malformed seal")
endif()

list(SUBLIST rows 0 ${seal_index} body_rows)
list(JOIN body_rows "\n" body)
string(APPEND body "\n")
string(SHA256 actual_seal "${body}")
if(NOT actual_seal STREQUAL expected_seal)
  message(FATAL_ERROR "CTest route index seal does not match its rows")
endif()

set(names)
set(targets)
set(tests)
if(seal_index GREATER 1)
  math(EXPR last_route "${seal_index} - 1")
  foreach(index RANGE 1 ${last_route})
    list(GET rows ${index} row)
    string(REPLACE "\t" ";" fields "${row}")
    list(LENGTH fields field_count)
    if(NOT field_count EQUAL 6)
      message(FATAL_ERROR "Malformed CTest route row: ${row}")
    endif()
    list(GET fields 0 kind)
    list(GET fields 1 name)
    list(GET fields 2 route_targets)
    list(GET fields 3 resources)
    list(GET fields 4 timeout)
    list(GET fields 5 runner)
    if(NOT kind STREQUAL "route" OR
       NOT name MATCHES "^[A-Za-z0-9][A-Za-z0-9_.-]*$" OR
       NOT route_targets MATCHES
         "^(-|[A-Za-z0-9_.+-]+(,[A-Za-z0-9_.+-]+)*)$" OR
       NOT resources MATCHES
         "^(-|[A-Za-z0-9_.-]+(,[A-Za-z0-9_.-]+)*)$" OR
       NOT timeout MATCHES "^[1-9][0-9]*$" OR
       NOT runner MATCHES "^(direct|accel)$")
      message(FATAL_ERROR "Malformed CTest route field: ${row}")
    endif()
    list(FIND names "${name}" duplicate)
    if(NOT duplicate EQUAL -1)
      message(FATAL_ERROR "Duplicate CTest route name: ${name}")
    endif()
    list(APPEND names "${name}")

    string(REPLACE "," ";" resource_list "${resources}")
    list(FIND resource_list "rund_accel" accel_resource)
    if(runner STREQUAL "accel")
      if(accel_resource EQUAL -1 OR NOT timeout STREQUAL "1800")
        message(FATAL_ERROR
          "Accelerator CTest route lost its resource or timeout: ${name}")
      endif()
    elseif(NOT accel_resource EQUAL -1)
      message(FATAL_ERROR
        "Direct CTest route owns the accelerator resource: ${name}")
    endif()

    if(name MATCHES "${pattern}")
      list(APPEND tests "${name}")
      if(NOT route_targets STREQUAL "-")
        string(REPLACE "," ";" route_targets "${route_targets}")
        list(APPEND targets ${route_targets})
      endif()
    endif()
  endforeach()
endif()

set(output_rows)
if(tests)
  list(REMOVE_DUPLICATES tests)
  list(SORT tests)
  foreach(test IN LISTS tests)
    list(APPEND output_rows "test\t${test}")
  endforeach()
endif()
if(targets)
  list(REMOVE_DUPLICATES targets)
  list(SORT targets)
  foreach(target IN LISTS targets)
    list(APPEND output_rows "target\t${target}")
  endforeach()
endif()
if(output_rows)
  list(SORT output_rows)
  list(JOIN output_rows "\n" output)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${output}")
endif()
